= 召唤
:stem:

> 这篇文章是关于召唤技能的。关于技能的训练，请参阅xref:../练级/召唤-练级.adoc[召唤/训练]。

召唤是一项技能，允许你制造用于各种使魔的召唤符文，这些使魔在佩戴时会提供各种类型的加成效果。在单个装备栏中可以带两种类型的符文。当同时装备某些使魔的组合时，除了它们单独的常规加成外，还会提供一种连携效果。

==	机制

===	收集召唤印记

为了制造某个召唤兽的召唤石板，玩家必须至少拥有相应的召唤印记之一。召唤兽的召唤印记是通过在召唤技能以外的技能中获得经验来获得的。召唤印记页面可以显示玩家被允许召唤的召唤兽的印记可以在哪些技能中找到。

在玩家达到制作相应石板的级别之前，无法找到召唤印记（如果在冒险模式中玩，玩家还必须解锁召唤技能才能开始寻找召唤印记）。在级别1时，有两个可以找到的印记：戈耳宾小偷的印记，这是在使用增加攻击、力量或防御经验的战斗方式进行训练时发现的；以及恩特树人的印记，这是在伐木时发现的。

*一旦为某个召唤兽找到了第一个印记，玩家在制造至少一个该召唤兽的召唤石板之前将不再找到任何印记。*

召唤印记不是一个道具，不会存放到玩家的银行中。一旦找到，它们将填充进相应召唤兽印记级别的升级进度条。每级的印记数量和效益如下：

[%autowidth]
|===
|等级 |升级所需印记数量 |累计所需印记 |效果

|1
|1
|1
|解锁制作召唤石板的能力

|2
|5
|6
|解锁此召唤兽的1级连携

|3
|10
|16
|解锁此召唤兽的2级连携

|4
|15
|31
|解锁此召唤兽的3级连携

|5
|15
|46
|解锁此召唤兽的4级连携

|6
|15
|61
|解锁此召唤兽的5级连携
|===

请注意：

* 所有战斗技能（包括屠杀者技能）的印记在每次攻击中都有获得的机会，而不是只有在杀死怪物时才能获得。
* 屠杀者印记只能从玩家当前的屠杀者任务怪物那里获得，不能从其他屠杀者怪物那里找到。
* 只有在使用每次玩家攻击都要消耗点数的祝祭时才能找到祝祭印记。
* 在进行生活类魔法时才能找到魔法印记。
* 在从蛮族渔场的钓鱼区捕鱼时不能找到力量印记。

==== 印记发现的几率

每次行动发现印记的几率可以由以下公式算出：

[stem]
++++
\text{发现印记的几率} = \frac{\text{Action Time}}{(\text{Tier}+1)^2 \times 200} \times \text{Equipped Modifier}
++++

其中：

* *Tier* 是印记的级别
* *Equipped Modifier* 取决于：
** 如果正在为已装备的召唤物发现印记，并且该宠物是在非战斗技能中发现的，则为2.5
** 如果已装备的宠物是在战斗技能中发现的，则为2
** 否则为1
* *Action Time* 是行动所需的时间（以秒为单位），对于战斗技能来说，它等于玩家的攻击速度。请注意，对于以下技能，不管实际行动所需的时间是多少，该值都被固定为以下值：

[%autowidth]
|===
|技能 |每次行动的秒数

|生火
|指定木材基本燃烧间隔的 60%

|烹饪
|指定烹饪配方基本烹饪间隔的 85%

|锻造
|1.7

|弓匠
|1.3

|制造
|1.65

|符文锻造
|1.7

|草药学
|1.7

|召唤
|4.85
|===

*注意*：对于生火制作技能，最高的发现几率是在燃烧具有最高精通等级的木材时实现的，而不仅仅是选择燃烧时间最短的木材。请查看以下内容以获取更多信息。

===== 最大化印记发现几率

提高宠物随时间获取印记的几率可以通过以下方式实现：

* 装备相同宠物的符文石板。对于非战斗技能（除生活类魔法外），这将使几率增加2.5倍，对于战斗技能和生活类魔法，几率增加一倍。
* 选择生火技能中具有最高精通等级的木材进行燃烧。由于上面提到的行动时间对每种木材都不同，拥有最高精通等级的木材相对于基本燃烧间隔来说是最快的，从而最大化了印记几率。
* 减少以下消耗资源的技能的行动时间：烹饪、锻造、弓匠、制作、符文铸造和草药学。这将提高获得印记的速率。对于其他任何技能，行动时间的变化都不会影响获得印记的速率，尽管通常更长的行动时间通常更可取，以减少随时间消耗的符文石板数量。
* 对于战斗技能：
** 最大化玩家的命中几率将提高获得印记的速率，因为印记只在攻击成功命中时才会计算几率，而在未命中时一定不会获得。
** 使用具有特殊攻击的武器，可以进行多次攻击，但这不会增加发现印记的几率，因为用于除第一个攻击之外的后续攻击的行动时间是自上次攻击以来的时间，而不是基本攻击间隔。

===	获得召唤经验

一旦玩家拥有至少一个召唤印记，他们就可以开始提升召唤技能。有两种方式可以获得召唤经验：制作召唤石板和使用召唤石板。然而请注意，只有制作石板会获得精通经验。

==== 制作召唤石板

相对于其他工艺技能而言，制作召唤石板是一个较慢的过程。默认情况下，每个行动需要5秒钟，并产生25个石板。如果玩家拥有“林道远足(6FT)”，则可以将间隔减少到4.85秒。

通过一系列方式，可以进一步减少间隔时间，包括使用来自商店以屠杀者硬币购买的死灵法师套装（当装备全套时，提供1秒的间隔缩短），通过“符文匍匐(12RC)”灵巧障碍获得的5%，通过奇米康星座获得的5%，通过至尊召唤技能斗篷获得的10%，通过鹰和狐狸的连携作用获得的10%，通过精英专业支柱获得的3%，以及通过哈罗德获得的2%。当所有奖励都生效时，间隔时间可以减少至1.25秒。

可以通过多种方式增加制作的石板数量，包括”遗迹远足8RT“灵巧障碍、召唤的95%熟练池检查点、召唤技能斗篷、死灵法师套装和死灵法师药水。

无论制作的石板数量多少，每个操作都会获得相同数量的经验点数。获得的基本经验点数等于:

。

====	Using Familiars

===	Unlocking And Using Synergies

==	Summoning Marks

==	Summoning Tablets

==	Synergies

==	Mastery Unlocks

===	Item Mastery Unlocks

===	Mastery Pool Checkpoints

==	Skillcape

==	Pet

==	Potion

==	Skill Boosts
