= 召唤
:stem:

https://wiki.melvoridle.com/w/Summoning[原文地址,window=_blank]

IMPORTANT: 该页面已过期(v1.1.2)

> 这篇文章是关于召唤技能的。关于技能的训练，请参阅xref:../练级/召唤-练级.adoc[召唤/训练]。

召唤是一项技能，允许你制造用于各种使魔的召唤符文，这些使魔在佩戴时会提供各种类型的加成效果。在一套装备栏中可以带两种类型的符文。当同时装备某些使魔的组合时，除了它们单独的常规加成外，还会提供额外的连携效果。

== 机制

[[收集召唤印记]]
===	收集召唤印记

为了制造某个召唤兽的召唤石板，玩家必须至少拥有相应的召唤印记之一。召唤兽的召唤印记是通过在召唤技能以外的技能中获得经验来获得的。召唤印记页面可以显示玩家被允许召唤的召唤兽的印记可以在哪些技能中找到。

在玩家达到制作相应石板的级别之前，无法找到召唤印记（如果在冒险模式中玩，玩家还必须解锁召唤技能才能开始寻找召唤印记）。在级别1时，有两个可以找到的印记：戈耳宾小偷的印记，这是在使用增加攻击、力量或防御经验的战斗方式进行训练时发现的；以及恩特树人的印记，这是在伐木时发现的。

*一旦为某个召唤兽找到了第一个印记，玩家在制造至少一个该召唤兽的召唤石板之前将不再找到任何印记。*

召唤印记不是一个道具，不会存放到玩家的银行中。一旦找到，它们将填充进相应召唤兽印记级别的升级进度条。每级的印记数量和效益如下：

[[action-time-table]]
[%autowidth]
|===
|等级 |升级所需印记数量 |累计所需印记 |效果

|1
|1
|1
|解锁制作召唤石板的能力

|2
|5
|6
|解锁此召唤兽的1级连携

|3
|10
|16
|解锁此召唤兽的2级连携

|4
|15
|31
|解锁此召唤兽的3级连携

|5
|15
|46
|解锁此召唤兽的4级连携

|6
|15
|61
|解锁此召唤兽的5级连携
|===

请注意：

* 所有战斗技能（包括屠杀者技能）的印记在每次攻击中都有获得的机会，而不是只有在杀死怪物时才能获得。
* 屠杀者印记只能从玩家当前的屠杀者任务怪物那里获得，不能从其他屠杀者怪物那里找到。
* 只有在使用每次玩家攻击都要消耗点数的祝祭时才能找到祝祭印记。
* 在进行生活类魔法时才能找到魔法印记。
* 在从蛮族渔场的钓鱼区捕鱼时不能找到力量印记。

==== 印记发现的几率

每次行动发现印记的几率可以由以下公式算出：

[stem]
++++
\text{发现印记的几率} = \frac{\text{Action Time}}{(\text{Tier}+1)^2 \times 200} \times \text{Equipped Modifier}
++++

其中：

* *Tier* 是印记的级别
* *Equipped Modifier* 取决于：
** 如果正在为已装备的召唤物发现印记，并且该召唤石板是在非战斗技能中发现的，则为2.5
** 如果已装备的召唤石板是在战斗技能中发现的，则为2
** 否则为1
* *Action Time* 是行动所需的时间（以秒为单位），对于战斗技能来说，它等于玩家的攻击速度。请注意，对于以下技能，不管实际行动所需的时间是多少，该值都被固定为以下值：

[%autowidth]
|===
|技能 |每次行动的秒数

|生火
|指定木材基本燃烧间隔的 60%

|烹饪
|指定烹饪配方基本烹饪间隔的 85%

|锻造
|1.7

|弓匠
|1.3

|制造
|1.65

|符文锻造
|1.7

|草药学
|1.7

|召唤
|4.85
|===

*注意*：对于生火制作技能，最高的发现几率是在燃烧具有最高精通等级的木材时实现的，而不仅仅是选择燃烧时间最短的木材。请查看以下内容以获取更多信息。

===== 最大化印记发现几率

提高召唤石板随时间获取印记的几率可以通过以下方式实现：

* 装备相同召唤石板的符文石板。对于非战斗技能（除生活类魔法外），这将使几率增加2.5倍，对于战斗技能和生活类魔法，几率增加一倍。
* 选择生火技能中具有最高精通等级的木材进行燃烧。由于上面提到的行动时间对每种木材都不同，拥有最高精通等级的木材相对于基本燃烧间隔来说是最快的，从而最大化了印记几率。
* 减少以下消耗资源的技能的行动时间：烹饪、锻造、弓匠、制作、符文铸造和草药学。这将提高获得印记的速率。对于其他任何技能，行动时间的变化都不会影响获得印记的速率，尽管通常更长的行动时间通常更可取，以减少随时间消耗的符文石板数量。
* 对于战斗技能：
** 最大化玩家的命中几率将提高获得印记的速率，因为印记只在攻击成功命中时才会计算几率，而在未命中时一定不会获得。
** 使用具有特殊攻击的武器，可以进行多次攻击，但这不会增加发现印记的几率，因为用于除第一个攻击之外的后续攻击的行动时间是自上次攻击以来的时间，而不是基本攻击间隔。

===	获得召唤经验

一旦玩家拥有至少一个召唤印记，他们就可以开始提升召唤技能。有两种方式可以获得召唤经验：制作召唤石板和使用召唤石板。然而请注意，只有制作石板会获得精通经验。

==== 制作召唤石板

相对于其他工艺技能而言，制作召唤石板是一个较慢的过程。默认情况下，每个行动需要5秒钟，并产生25个石板。如果玩家拥有“林道远足(6FT)”，则可以将间隔减少到4.85秒。

通过一系列方式，可以进一步减少间隔时间，包括使用来自商店以屠杀者硬币购买的死灵法师套装（当装备全套时，提供1秒的间隔缩短），通过“符文匍匐(12RC)”灵巧障碍获得的5%，通过奇米康星座获得的5%，通过至尊召唤技能斗篷获得的10%，通过鹰和狐狸的连携作用获得的10%，通过精英专业灵巧柱获得的3%，以及通过哈罗德获得的2%。当所有奖励都生效时，间隔时间可以减少至1.25秒。

可以通过多种方式增加制作的石板数量，包括”遗迹远足8RT“灵巧障碍、召唤的95%熟练池检查点、召唤技能斗篷、死灵法师套装和死灵法师药水。

无论制作的石板数量多少，每个操作都会获得相同数量的经验点数。获得的基本经验点数等于:

[stem]
++++
\text{获取经验} = 5 + 2 \times \lfloor \text{召唤等级需求} \times 0.2 \rfloor
++++

例如，制作一个猪召唤石板(需要25级召唤等级)可以获得 stem:[5+2 \times \lfloor 25 \times 0.2 \rfloor = 15 \text{点经验}]：

==== 使用召唤石板

一旦创建了召唤石板，就可以通过使用这些召唤石板来更快地获得召唤经验。每次消耗石板的次数时都会获得经验点数。对于非战斗石板，这发生在玩家执行相关技能的动作时。对于战斗石板，这发生在每次召唤石板的攻击条读满后，这需要3秒的时间。此外，邪教徒和女巫召唤石板将在执行每个生活类魔法动作时消耗，比通过战斗快1秒，但不会从石板中获得其他好处。

获得的经验遵循一个公式，该公式基于召唤物的等级和动作所需的时间（以秒为单位）：

[stem]
++++
\text{获取经验} = \frac{\text{行动所需的时间} \times \text{召唤等级需求} \times 10}{\text{召唤等级需求} + 10}
++++

当消耗一个符文石板时，有些技能会使用固定值来表示每个动作的时间，不考虑玩家的加成，类似于精通经验。具体来说，这适用于消耗资源的技能。这些技能及其动作时间 xref:action-time-table[如上面的表格所示]。

例如，如果装备了猪召唤符文石板（需要召唤等级25）进行烹饪，即使玩家的实际烹饪动作时间是默认的3秒，所获得的经验点数将为 stem:[\frac{2.55 \times 25 \times 10}{25 + 10} = 18.21经验]。

当符文石板作为连携作用的一部分使用时，每个使用的符文石板都将获得经验点数。这两个符文石板将使用相同的动作时间，这要么是 xref:action-time-table[表格中列出] 技能的固定值，要么是所有其他技能的实际动作时间。

===	解锁并使用连携效果

_- 主要文章：**连携效果**_

一些召唤石板在同时使用时会产生额外的效果。这些组合效果称为连携效果，可以通过同时达到两者的印记所需等级来解锁。即使两个召唤石板都已装备，连携效果也不会发生，除非已经到达印记所需等级以解锁。

解锁连携效果所需的印记级别等于连携效果中另一个召唤石板的级别加一。例如，要解锁 *哥布林小偷*（1级召唤）和 *牛头人*（2级召唤）之间的连携效果，需要 *哥布林小偷* 印记级别达到3，*牛头人* 印记级别达到2。

在使用已解锁的连携效果时，将使用每个召唤石板的一次次数，并使用此次行动所对应石板的额外一次次数。例如，当使用**恩特树人** + *鼹鼠* 的连携效果（每次伐木动作有2%的几率获得随机宝石）时，每个动作将使用两个**恩特树人**召唤石板和一个**鼹鼠**召唤石板。

每个使用的召唤石板都会获得经验点数，这意味着由于消耗了更多召唤石板，激活连携效果可以更快地获得经验点数。由于获得的经验点数与动作时间成比例，因此可以通过选择最长的动作来最大化每个召唤石板获得的经验点数。

== 召唤印记

印记可以通过执行与印记相关的技能内的任何动作来发现，如下面表格的“发现位置”列所示。有关如何发现印记的更多信息可以在 xref:收集召唤印记[收集召唤印记] 部分中找到。

[%autowidth]
|===
|印记 |召唤等级 |发现位置
|哥布林小偷|1|攻击、力量、防御
|恩特树人|1|伐木
|鼹鼠|5|采矿
|邪教徒|5|魔法
|狼|15|攻击、远程
|章鱼|15|钓鱼
|牛头人|25|力量
|猪|25|烹饪
|乌鸦|35|符文锻造
|半人马|35|远程
|女巫|45|魔法
|小矮妖|45|扒窃
|猴子|55|制造
|独眼巨人|55|屠杀者
|牦牛|65|防御
|火蜥蜴|65|锻造
|乌龟|70|攻击、远程、魔法
|独角兽|80|祝祭
|熊|80|草药学
|恶魔|90|生火
|龙|90|生命值
|雷霆之魂|100|攻击、远程、魔法
|鹰|100|灵巧
|猫头鹰|105|星象学
|海妖|105|力量、远程、魔法
|蜘蛛|110|防御、远程、魔法
|海狸|110|弓匠
|狐狸|115|召唤
|幽灵|115|祝祭
|===

== 召唤石板

[%autowidth]
|===
|名称 |等级 |级别 |效果 |最大伤害 |晶石消耗 |次级材料 |制造经验
|哥布林小偷|1|1|+30成功命中敌人时的金币掉落|21|6红色晶石|各种匕首|5
|恩特树人|1|1|+10%几率通过伐木额外获得+1资源(此效果无法翻倍)||6绿色晶石|各种原木|5
|鼹鼠|5|1|+3%几率通过采矿额外获得+1资源(此效果无法翻倍)||6绿色晶石|各种矿石|7
|邪教徒|5|1|+10%全局闪避几率|40|6红色晶石|16眼球|7
|狼|15|1|+2%生命偷取|59|6红色晶石|各种熟鱼|11
|章鱼|15|1|+3%几率通过钓鱼额外获得+1资源(此效果无法翻倍)||6绿色晶石|各种生鱼|11
|牛头人|25|2|+3%近战最大伤害,+3%近战精准|78|8红色晶石,6蓝色晶石|各种战斧|15
|猪|25|2|+10%几率留存烹饪资源||8绿色晶石,6银色晶石|各种熟鱼|15
|乌鸦|35|2|+2符文锻造时获得额外同类型符文||8绿色晶石,6银色晶石|各种符文|19
|半人马|35|2|+3%远程精准,+3%远程最大伤害|97|8红色晶石,6蓝色晶石|各种弓|19
|女巫|45|2|+3%魔法精准,+3%魔法最大伤害|116|8红色晶石,6蓝色晶石|各种符文|23
|小矮妖|45|2|+50扒窃获得的金币||8绿色晶石,6银色晶石|1000金币|23
|猴子|55|3|+10%几率通过制造获得双倍掉落||10绿色晶石,8银色晶石,6黑色晶石|各种首饰|27
|独眼巨人|55|3|+10%屠杀者硬币|135|10红色晶石,8蓝色晶石,6金色晶石|1000屠杀者硬币|27
|牦牛|65|3|+1%伤害减免|154|10红色晶石,8蓝色晶石,6金色晶石|各种盾|31
|火蜥蜴|65|3|+5%几率留存锻造资源||10绿色晶石,8银色晶石,6黑色晶石|各种矿锭|31
|乌龟|70|1|+50%召唤使魔对屏障的额外伤害|160|14红色晶石,6蓝色晶石|各种屏障宝石|33
|独角兽|80|3|+50%生命值再生|173|10红色晶石,8蓝色晶石,6金色晶石|22神圣灰烬|37
|熊|80|3|+5%几率留存草药学资源||10绿色晶石,8银色晶石,6黑色晶石|各种草药|37
|恶魔|90|3|-5%生火间隔||10绿色晶石,8银色晶石,6黑色晶石|各种宝石|41
|龙|90|3|+10%几率攻击时附加燃烧状态|192|10红色晶石,8蓝色晶石,6金色晶石|5龙骨|41
|雷霆之魂|100|4|+5%几率在攻击时造成1回合的眩晕效果(每回合1次)|202|12红色晶石,10蓝色晶石,8金色晶石|40雷霆符文|45
|鹰|100|4|-5%灵巧间隔||12绿色晶石,10银色晶石,8黑色晶石|50羽毛|45
|猫头鹰|105|4|-5%星象学间隔||12绿色晶石,10银色晶石,8黑色晶石|50星尘**或**1黄金星尘|47
|海妖|105|4|+5%几率在攻击时造成1回合的沉睡效果(每回合1次)|207|12红色晶石,10蓝色晶石,8金色晶石|各种99级以上的生鱼|47
|蜘蛛|110|5|+5%几率在攻击时造成15%的减速效果持续2个攻击(每回合1次) +
+5%几率在进行攻击时施加中毒效果|212|14红色晶石,12蓝色晶石,10金色晶石|20蜘蛛女王卵|49
|海狸|110|5|+5%几率通过锻造获得双倍掉落||14绿色晶石,10银色晶石,8黑色晶石|各种标枪|49
|狐狸|115|5|+5召唤最大伤害,-5%召唤间隔||14绿色晶石,10银色晶石,8黑色晶石|各种晶石|51
|幽灵|115|5|-5%敌人伤害减免|217|14红色晶石,12蓝色晶石,10金色晶石|1虚无质|51
|===

== 连携效果

[%autowidth]
|===
|使魔1 |使魔2 |效果 |需求
|乌龟|半人马|+60使用远程攻击时使魔对屏障的伤害|70级召唤,3级乌龟印记,2级半人马印记
|乌龟|独眼巨人|+30%屠杀者任务时使魔对屏障的伤害|70级召唤,4级乌龟印记,2级独眼巨人印记
|===

== 精通解锁

===	Item Mastery Unlocks

===	精通池节点

== 技能斗篷

== 宠物

**Tim the Wolf**只能在制作召唤石板时解锁，而不能在使用召唤石板时解锁。

**Mark**的获取方式与其他技能宠物不同，只有当玩家在基础游戏的召唤标记中达到4级标记等级时才会解锁。

[%autowidth]
|===
|名称|效果
|Tim the Wolf|-1在制作石板时的晶石消耗
|Mark|+10%几率留存召唤资源
|===

== 药水

**死灵法师药水**可以用来增加每次制造召唤石板的数量。

[%autowidth]
|===
3+^.^|死灵法师药水
^.^|级别 ^.^|次数 ^.^|效果
|1|15|+1召唤石板制作的基础数量
|2|30|+2召唤石板制作的基础数量
|3|45|+3召唤石板制作的基础数量
|4|60|+4召唤石板制作的基础数量
|===

== 技能加成
