= 灵巧

[%autowidth]
|===
|等级|    课程变更|    消耗|    需求|    全部课程
|1-10|    建造 渔网|    金币10k||    渔网
|10-20|    建造 平衡梁|    金币50k||    渔网, 平衡梁
|20-30|    建造 深坑跳远|金币150k +
生鲱鱼300 +
生鲑鱼300    ||    渔网, 平衡梁, 深坑跳远
|30-40    |建造 沟壑跳远|    金币250k +
心智符文500||        渔网, 平衡梁, 深坑跳远, 沟壑跳远
|40-50|    建造 爬树|    金币500k +
桃花心木1000 +
铁制箭矢2000 +
混乱符文2000|    生火60|    渔网, 平衡梁, 深坑跳远, 沟壑跳远, 爬树
|50-60|    建造 木筏漂流|    金币1,000k +
西瓜3000|    伐木60|    渔网, 平衡梁, 深坑跳远, 沟壑跳远, 爬树, 木筏漂流
|60-70|    建造 灼热陷阱|    金币2,500k|    |    渔网, 平衡梁, 深坑跳远, 沟壑跳远, 爬树, 木筏漂流, 灼热陷阱
|70-80|    建造 树木悬挂|    金币5,000k +
巴伦托尔草5000|    伐木80 +
生火80|    渔网, 平衡梁, 深坑跳远, 沟壑跳远, 爬树, 木筏漂流, 灼热陷阱, 树木悬挂
|80-90|    建造 冰川跳跃 +
用 平衡翘板 替换 深坑跳远 +
用 翻山越岭 替换 爬树 +
用 树顶平衡 替换 木筏漂流    |金币11,650k +
螃蟹2500 +
煤炭5000 +
钻石2000 +
骨头1000    |烹饪60 +
采矿60 +
屠杀者60 +
扒窃60    |渔网, 平衡梁, 平衡翘板, 沟壑跳远, 翻山越岭, 树顶平衡, 灼热陷阱, 树木悬挂, 冰川跳跃
|90-100    |建造 巨石挪动 +
用 尖刺跳跃 替换 树木悬挂|    金币25,000k +
屠杀者硬币150k +
龙岩锭10k +
红杉木10k +
绿宝石2k|    伐木99 +
生火99 +
防御70 +
祝祭70|    渔网, 平衡梁, 平衡翘板, 沟壑跳远, 翻山越岭, 树顶平衡, 灼热陷阱, 尖刺跳跃, 冰川跳跃, 巨石挪动
|100-105|    建造 森林迷宫|    金币30,000k +
屠杀者硬币500k +
岩浆鱼8000 +
刚玉锭6000    |烹饪100 +
屠杀者100 +
锻造100|    渔网, 平衡梁, 平衡翘板, 沟壑跳远, 翻山越岭, 树顶平衡, 灼热陷阱, 尖刺跳跃, 冰川跳跃, 巨石挪动, 森林迷宫
|105-110|    建造 森林迷宫 +
用 舒缓慢跑 替换 尖刺跳跃|    金币55000000  +
山铜5000 +
魔法树5000||        渔网, 平衡梁, 平衡翘板, 沟壑跳远, 翻山越岭, 树顶平衡, 灼热陷阱, 舒缓慢跑, 冰川跳跃, 巨石挪动, 森林迷宫, 森林迷宫
|110-115|    建造 洞窟陷阱|    金币75000000||        渔网, 平衡梁, 平衡翘板, 沟壑跳远, 翻山越岭, 树顶平衡, 灼热陷阱, 舒缓慢跑, 冰川跳跃, 巨石挪动, 森林迷宫, 森林迷宫, 洞窟陷阱
|115-118|    建造 冰冻攀爬|    金币150000000 +
蔚蓝石5000 +
钯金锭15000 +
纯净精华20000|    防御110 +
远程110 +
魔法110|    渔网, 平衡梁, 平衡翘板, 沟壑跳远, 翻山越岭, 树顶平衡, 灼热陷阱, 舒缓慢跑, 冰川跳跃, 巨石挪动, 森林迷宫, 森林迷宫, 洞窟陷阱, 冰冻攀爬
|118-120|    建造 峻岭远足|    金币200000000 +
陨石锭10000 +
陨石标枪15000 +
亡魂木25000|    锻造115 +
弓匠115 +
制造115|    渔网, 平衡梁, 平衡翘板, 沟壑跳远, 翻山越岭, 树顶平衡, 灼热陷阱, 舒缓慢跑, 冰川跳跃, 巨石挪动, 森林迷宫, 森林迷宫, 洞窟陷阱, 冰冻攀爬, 峻岭远足
|===