= 生活类魔法

== Training

1. Do *Alt. Magic* until 43 *Magic* for *Wind Wave*. Upgrade your wands, spells, and armour accordingly as your *Magic* level increases.
2. Make the *Air Adept Wizard Hat* *Air Adept Wizard Robes* *Air Adept Wizard Bottoms* *Air Adept Wizard Boots* wizard gear and choose a monster to fight with the [战斗模拟器]. It will likely be the *Giant Crab*.

The comparison of *Combat* and *Alt. Magic* can be found in the following spreadsheet: ([https://docs.google.com/spreadsheets/d/11wEZc6q7EkeWyaRVg5vIBFo50hDKx_4uq3PgIXztSgk/edit?usp=sharing link]).

The {{Icon|Combat|nolink=true}} method starts to be better than {{Skill|Alt. Magic|nolink=true}} in terms of XP gain almost right from the start. However, in order to maintain that edge over the {{Skill|Alt. Magic|nolink=true}} method, you need to check the game more often.

For {{Skill|Alt. Magic|nolink=true}}, you need to prepare a disposable item, such as {{ItemIcon|Cheese}} from the [[Shop]], then craft a {{ItemIcon|Staff of Air}} and some {{ItemIcon|Nature Rune|Nature Runes}}. After that, you can leave the {{Icon|Just Learning|type=spell}} spell to idle. The same steps apply to most other {{Skill|Alt. Magic|nolink=true}} skills - you come back, prepare a disposable item and runes for the next idle session, and idle.

For {{Icon|Combat|nolink=true}}, you need to change your gear regularly in order to have an advantage over the {{Skill|Alt. Magic|nolink=true}} option. Depending in your involvement, you can go through the whole spectrum of Wizard Robes because each of them has slightly higher Magic requirement than the previous one. In addition to that, you need to prepare food and to come back before it runs out.

After {{SkillReq|Magic|14}}, the {{Icon|Combat|nolink=true}} method starts to have an advantage. If you have food, runes, and you are okay with checking the game every so often, then you can switch to {{Icon|Combat|nolink=true}} straight after {{SkillReq|Magic|14}}.

For the approach with less involvement, {{Icon|Alternative Magic|type=skill|Alt. Magic|nolink=true}} is a way to go - use the highest level spell you can and stop on {{Icon|Blessed Offering|type=spell}} to accumulate {{Skill|Prayer}} points. You will need at least 250,000 prayer points if you are just starting, so you can continue casting this spell until {{SkillReq|Magic|78}} when you unlock the {{ItemIcon|Fire Expert Wizard Robes|Fire Expert}} gear to prevent any further armour swaps.

== Alternative Training (delayed Magic Leveling) ==
Alternatively, players can delay their {{Skill|Magic}} leveling for some time, training after reaching 100 {{Icon|Volcanic Cave|type=dungeon}} clears for ancient magic. You will need {{SkillReq|Runecrafting|85}} in order to craft {{ItemIcon|Ancient Rune|Ancient Runes}}. One advantage is saving on [[Bank]] space, as you will not need a large stockpile of runes to begin with. You will also have the opportunity to acquire many powerful items to accelerate your leveling, including {{ItemIcon|Ring of Spirit Power}}.

===Required Skills===
* {{SkillReq|Thieving|75}} for {{ItemIcon|Wizard's Sigil}}, stolen from {{Icon|Wizard|type=thieving}}. You will also likely acquire {{ItemIcon|Book of Scholars}} (a useful skill XP boosting item), {{ItemIcon|Amulet of Incantation}}, {{ItemIcon|Wizard's Scroll|Wizard's Scrolls}}, {{ItemIcon|Prayer Scroll|Prayer Scrolls}}, and a large assortment of runes.
* {{SkillReq|Crafting|90}} for {{ItemIcon|Ring of Spirit Power}}.
* {{SkillReq|Runecrafting|80}} for {{ItemIcon|Spirit Rune|Spirit Runes}}.

===Recommended Skills===
* {{SkillReq|Herblore|65}} for potions such as {{ItemIcon|Magic Assistance Potion|Magic Assistance Potions|img=Magic Assistance Potion IV}}, {{ItemIcon|Magic Damage Potion|Magic Damage Potions|img=Magic Damage Potion IV}}, or any other potions you prefer.
* {{SkillReq|Summoning|80}} to unlock the {{ItemIcon|Crow}} and {{ItemIcon|Bear}} Synergy for {{Skill|Runecrafting}}, as well as many {{Icon|Combat|nolink=true}} related synergies.
* {{SkillReq|Ranged|40}} or more to start farming monster drops that will be used for {{SkillReq|Magic|1}} gear.

===Gear===

{| class="wikitable stickyHeader"
|- class="headerRow-0"
! Item name !! Gear Slot !! Acquisition
|-
| Ring || {{ItemIcon|Ring of Spirit Power}} || {{SkillReq|Crafting|90}}
|-
| Head || {{ItemIcon|Air Acolyte Wizard Hat}} || {{SkillReq|Runecrafting|1}} or {{Skill|Thieving}} from {{Icon|Acolyte|type=thieving}}
|-
| Boots || {{ItemIcon|Air Acolyte Wizard Boots}} ||  {{SkillReq|Runecrafting|4}} or {{Skill|Thieving}} from {{Icon|Acolyte|type=thieving}}
|-
| Legs || {{ItemIcon|Air Acolyte Wizard Bottoms}} || {{SkillReq|Runecrafting|7}} or {{Skill|Thieving}} from {{Icon|Acolyte|type=thieving}}
|-
| Chest || {{ItemIcon|Air Acolyte Wizard Robes}} || {{SkillReq|Runecrafting|11}} or {{Skill|Thieving}} from {{Icon|Acolyte|type=thieving}}
|-
| Weapon ||{{ItemIcon|Staff of Air}} || {{SkillReq|Runecrafting|1}} or {{Icon|Combat|killing|nolink=true}} {{Icon|Fairy|type=monster}}
|-
| rowspan="3" | Back ||  {{ItemIcon|Enchanted Cape}} ||  {{Icon|Combat|Killing|nolink=true}} {{Icon|Master Wizard|type=monster}}
|-
| {{ItemIcon|Firemaking Skillcape}} || {{SkillReq|Firemaking|99}}
|-
| {{ItemIcon|Skull Cape}} || {{Skill|Slayer}} Points
|-
| Gloves || {{ItemIcon|Elementalist Gloves}} ||  {{Icon|Combat|Killing|nolink=true}} {{Icon|Elementalist|type=monster}}
|-
| Amulet || {{ItemIcon|Amulet of Looting}} ||  {{Icon|Spider Forest|type=dungeon}} dungeon
|}

===Strategy===

Farm the {{Icon|Giant Crab|type=monster}} using {{Icon|Wind Strike|type=spell}}, or the {{Icon|Mummy|type=monster}} if you want to farm {{ItemIcon|Amulet of Strength|Amulets of Strength}}. This can be done all the way until {{SkillReq|Magic|70}}, but you can actively switch targets and upgrade your gear for faster leveling. Switch to higher level Wind spells if you choose to do this. This can use up to 4500 runes per hour assuming no conservation bonuses. Food should not be necessary unless you are switching targets actively, but it's always safer to have some.

{{SkillGuideMenu}}
{{Menu}}
[[Category:Guides]]
[[Category:Skill Training]]
