= 草药学

https://wiki.melvoridle.com/w/Herblore/Training[原文地址]

== 练级

由于草药的主要来源是__**农务**__，草药通常是草药学练级速度的主要瓶颈。因此，建议最大化每颗草药的经验值，而不是仅仅制作提供最多经验值的药水。

在决定种植哪种草药时，宗旨是种植你当前可以制作的最高等级的药水所需要的草药。
例如，虽然__**莱蒙泰勒草**__在__**草药学**__等级40开始就可以用于制作__**渔夫药水**__，并获得36点经验值，但是在草药学等级达到45级之后，还可以做__**妙手空空药水**__，这个药水明显更好，因为它只使用一颗草药而不是两颗，因此每颗草药获得的经验值更多。

另一个技巧是每种类型的草药仅种植您需要的数量。例如，一旦您有足够数量的__**盖鲁姆草**__来达到草药学等级15，您就可以切换到酸模草了。

请注意，这些指南只应在您的目标是尽快获得草药学经验时遵循。否则，最好还是制作您将会用到的药水，按部就班的获取经验来练级。

但是，如果您准备了大量的草药库存，下表显示了高经验值收益率的技能药水的建议，这些药水不具有不方便的辅助材料成本。通常，战斗药水的资源成本较高，实际使用较少，即使它们每次制作的经验值更多。

[%autowidth]
|===
^.^s|等级 ^.^s|药水 ^.^s|经验 ^.^s|材料
| 1-20
| 鸟巢药水
| 5
| 盖鲁姆草894, 土豆种子1788

| 20-32
| 恒温药水
| 18
| 酸模草1332, 桃花心木1998

| 32-40
| 丰盛药水
| 28
| 曼塔里姆草742, 剑鱼1484

| 40-42
| 渔夫药水
| 33
| 莱蒙泰勒草462, 生螃蟹462

| 42-49
| 老练弓匠药水
| 39
| 莱蒙泰勒草2370, 弓弦2370

| 49-53
| 制造药水
| 41
| 莱蒙泰勒草1095, 皮革3285

| 53-62
| 精雕细琢药水
| 53
| 奥克西利姆草3721, 煤炭7442, 金矿3721

| 62-71
| 心灵手巧药水
| 61
| 波拉克希草15760, 生毒鱼7880

| 71-74
| 草药学药水
| 99
| 匹格泰勒草8541

| 74-99
| 丰饶收获药水
| 112
| 匹格泰勒草106591, 活血草213182, 胡萝卜213182
|===

== 加成效果

=== 经验

|===
^.^s|名称 ^.^s|类型 ^.^s|经验加成 ^.^s|其它修正

| 深坑跳远 |灵巧障碍 3级 |+3% 全局技能经验 |-4% 灵巧技能经验

| 泥地匍匐 |灵巧障碍 4级 |+2% 草药学技能经验 |-10% 农务产量<br>+3% 几率留存草药学资源<br>+2% 草药学技能经验<br>+2% 草药学专精经验

| 爬树 |灵巧障碍 5级 |+4% 全局技能经验 |-10% Ammo Preservation<br>-10% Chance to Preserve Resources in Skills<br>-10% Rune Preservation<br>+3% Global Mastery XP

| 舒缓满跑 |灵巧障碍 8级 |+5% 全局技能经验 |-6% 全局专精经验
|===

