= 熔岩洞窟/指南

https://wiki.melvoridle.com/w/Volcanic_Cave/Guide[原文地址,window=_blank]

这份指南的目标是自动挂机该副本。如果您想手动进行，要求会低很多，拥有更多DR（Damage Reduction伤害减免）仍然会更容易。

== 概括

- 获得 **落日刺剑**,
- 获得 **沙尘暴戒指**,
- 以近战的方式通关 100次 **熔岩洞窟**,
- 使用**Slicing Winds**继续farm**熔岩洞窟**。不要忘了激活**迸发**光环。

== 为什么要挂机熔岩洞窟?

每次通关后，您将获得**火焰披风**，可提供2%的DR(伤害减免)。

熔岩洞窟是您为迎接**大气之神地牢**而准备的场所。根据模拟结果，获得全部远古套装所需的平均次数是通关640次。以75%的概率获得全部远古套装需要通关817次，以95%的概率需要通关1377次。

这也是获得愤怒之符护符以制造元素圣斗士之怒（FEZ）的地方。请查看元素圣斗士之怒制作指南，以确定是否是您的最佳选择。

在您连续清除熔岩洞窟100次后，您将解锁古代魔法 - *Slicing Winds*,  *Icicle Volley* 和  *Ignite*。

- **Winds**可以在命中率不高的时候使用。只要您的命中率超过20k，它就不会miss；
- **Ignite**用于一击秒杀敌人；
- **Volley**用于其他情况。

古代魔法除了**战斗三角**外不受伤害增幅的影响。包括咒语、debuff、装备buff等。按照正常的游戏进程，在这个阶段它通常比其它基本魔法更强大。然而，由于古代魔法的非可扩展性质，它很容易被超越，使其过时。通常，当玩家获得**云爆法杖**时会发生这种情况，之后有许多新物品和增益效果 - 尤其是**灵魂之力戒指**，使基本魔法更强大成为可能。

== 挂机所需

熔岩洞窟中的怪物主要使用近战风格作为攻击手段。因此，由于战斗三角的惩罚，十分不推荐玩家使用远程来刷熔岩洞窟。

假设您已经升级了自动进食3级。

所有计算都是为了**硬核**/**冒险**模式而进行的。

如果您玩的是**标准**游戏模式，使用**近战**或者是生命值以及伤害减免较低，请使用 https://zxv975.github.io/CanIIdle/[Can I Idle]或**战斗模拟器**来检查您是否可以使用您的构建幸存下来。

=== 近战

**熔岩洞窟**通常使用**近战**武器，因为仅需要**99级锻造**技能就可以制作龙岩护甲，将他们**升级**后就可以获得30%的伤害减免。

下面是**熔岩洞窟**的**近战**挂机建议，它需要**820生命值**才能在全部游戏模式下生效。然而，请注意，即使伤害减免或生命值略低哪怕一点，也可能导致死亡，因为它与BOSS的最大伤害只有一线之差。请使用“ https://zxv975.github.io/CanIIdle/[Can I Idle] ”或“战斗模拟器”来检查您的属性是否可以挂机。此外，**沙尘暴戒指**对通关时间提升非常大。

[%autowidth]
|===
^.^|部位 ^.^|物品 ^.^|伤害减免(DR)%

^.^|头部
^.^|龙岩头盔(镀金)
^.^|6%

^.^|躯干
^.^|龙岩胸甲(镀金)
^.^|6%

^.^|裤子
^.^|龙岩胫甲(镀金)
^.^|6%

^.^|足部
^.^|龙岩靴(镀金)
^.^|6%

^.^|副手
^.^|龙岩盾牌(镀金)
^.^|6%

^.^|双手
^.^|圣骑士手套
^.^|4%

^.^|斗篷
^.^|骑士斗篷
^.^|1%

^.^|脖颈
^.^|精英防御护符
^.^|2%

^.^|戒指
^.^|沙尘暴戒指
^.^|0%

^.^|武器
^.^|落日刺剑
^.^|0%

2+^.^|总计
^.^|37%
|===

=== 熔岩洞窟之前的魔法

另一个可能的选择是**魔法**。从一开始就使用魔法挂机火山并不建议，因为它的打怪时间较慢，而且比可用的近战搭配更复杂。

**火焰专家巫师法袍**与**大气专家巫师装备**具有完全相同的属性。长袍的被动效果（对应法术的最小伤害+20）超过了更高级法术的伤害增加，因此，请使用您可用的最高级法术和长袍来进行组合。

如果可以的话，使用**灵魂之力戒指**代替**Aorpheat的图章戒指**。

要使用以下装备来挂机副本，您需要**780点生命值**和**虚弱III**处于激活状态。

[%autowidth]
|===
^.^|部位 ^.^|物品 ^.^|伤害减免(DR)%

^.^|头部
^.^|大气专家巫师帽
^.^|5%

^.^|躯干
^.^|大气专家巫师长袍
^.^|5%

^.^|裤子
^.^|大气专家巫师下装
^.^|5%

^.^|足部
^.^|大气专家巫师靴
^.^|5%

^.^|副手
^.^|龙岩盾牌(镀金)
^.^|6%

^.^|双手
^.^|(升级)古代龙皮护腕
^.^|6%

^.^|斗篷
^.^|骷髅斗篷
^.^|3%

^.^|脖颈
^.^|精英魔法护符
^.^|2%

^.^|戒指
^.^|Aorpheat的图章戒指
^.^|0%

^.^|武器
^.^|任何魔法武器
^.^|0%

2+^.^|总计
^.^|37%
|===

=== 100次熔岩洞窟后的魔法

在完成100次**熔岩洞窟**后，您将解锁**古代魔法**。

您在使用这个构建时的第一个目标是达到20k的精准，来使用“*Slicing Winds*”，这意味着这个法术将不会miss。因此，虽然这个构建最低只需要魔法等级72，但您最多需要魔法等级93或来自各种其他技能的多个精准奖励来达到20k的精准，包括：

- 魔法提升药水
- 星象学
- 祝祭
- 灵巧

如果您具备**880的生命值**和激活了**石肤**祝祭，那么您可以使用20k精准的“*Slicing Winds*”来farm熔岩洞窟。

要在33%的伤害减免情况下，在没有祝祭或药水的情况下farm地下城，需要**910的生命值**。您最大的威胁是“天机守护者普拉特”，该怪物的最大伤害接近您的自动进食阈值。

请检查您是否可以通过您可用的装备来满足精确需求，您可以使用战斗模拟器或检查您在非战斗状态下的统计数据。达到20k准确度非常重要，因为在这个数字之后，“Slicing Winds”将不会miss，成为这一进程阶段对抗副本的最高DPS法术。

[%autowidth]
|===
^.^|部位 ^.^|物品 ^.^|伤害减免(DR)%

^.^|头部
^.^|古代巫师帽
^.^|5%

^.^|躯干
^.^|古代巫师长袍
^.^|5%

^.^|裤子
^.^|古代巫师下装
^.^|5%

^.^|足部
^.^|古代巫师靴
^.^|5%

^.^|副手
^.^|荧菇盾牌
^.^|2%

^.^|双手
^.^|(升级)古代龙皮护腕
^.^|6%

^.^|斗篷
^.^|骷髅斗篷
^.^|3%

^.^|脖颈
^.^|精英魔法护符
^.^|2%

^.^|戒指
^.^|Aorpheat的图章戒指
^.^|0%

^.^|武器
^.^|魔杖(强力)
^.^|0%

2+^.^|总计
^.^|33%
|===

== 武器选择

这个表格显示了一些由于制作所需的消耗品所需的时间进行了调整的**战斗模拟**结果，同时对每个技能可用的精确奖励做出了一些假设。

您可以在这里查看电子表格。复制一份以调整资源值以适应您自己的情况，每个表格上都有一列，允许您输入自己的模拟结果（ https://docs.google.com/spreadsheets/d/1JAuROH4I_dNph9VwBXx7ffoGnWcoHlbsW0doWMBIPU0/edit?usp=sharing[链接] ）。

[%autowidth]
|===
^.^|武器 ^.^|每小时宝箱数量 ^.^|每小时最大宝箱数量 ^.^|与上一个相比的提升

^.^|魔杖(强力)
^.^|3.8
^.^|20+
^.^|0%

^.^|龙岩剑
^.^|7.6
^.^|24+
^.^|20%

^.^|龙爪
^.^|8
^.^|26.3+
^.^|9%

^.^|古代剑
^.^|8.16
^.^|26.2+
^.^|0%

^.^|落日刺剑
^.^|9.6
^.^|31.4+
^.^|19%

^.^|古代之爪
^.^|10
^.^|34.7+
^.^|10%

^.^|Slicing Winds
^.^|23.5
^.^|25.8
^.^|0%

^.^|Icicle Volley
^.^|18.1
^.^|28.3+
^.^|0%
|===

在玩家没有获得所有可用的增益效果之前，使用古代魔法的魔法构建通常比使用近战构建更好。由于施放所需的符文数量众多，以及古代魔法的不可增强的特性，最终它们在调整后的farm时间上落后于近战构建。

通常，食物的消耗约为每小时200k至250k生命值。

== 装备可选项

=== 手套

[%autowidth]
|===
^.^|物品 ^.^|伤害减免(DR)% ^.^|需求

^.^|圣骑士手套
^.^|4%
^.^|无

^.^|(升级)红龙皮护腕
^.^|4%
^.^|远程60级

^.^|(升级)黑龙皮护腕
^.^|5%
^.^|远程70级

^.^|(升级)古代龙皮护腕
^.^|6%
^.^|远程80级
|===


**古代龙皮装备**从**龙穴(副本)**掉落。您很可能需要它们来在**大气之神地牢**中挂机，所以最好现在就获取它们。

**红龙**和**黑龙**装备可以通过**制造**或从**蜘蛛森林(副本)**中掉落。

或者您也可以farm**圣骑士**以获得**圣骑士手套**。

=== 斗篷

[%autowidth]
|===
^.^|物品 ^.^|提升效果 ^.^|出处

^.^|骑士斗篷
^.^|1% DR
^.^|66级扒窃区域独特掉落

^.^|骷髅斗篷
^.^|3% DR
^.^|会降低近战精准

^.^|生火斗篷
^.^|经验加成
^.^|生火99级，无DR加成

^.^|黑曜石斗篷
^.^|节省少许食物
^.^|稀有掉落，无DR加成

^.^|火焰斗篷
^.^|2% DR
^.^|需要通关一次熔岩洞窟
|===

=== 靴子

靴子的选择有限，因为我们不希望伤害减免（DR）降低太多。

[%autowidth]
|===
^.^|物品 ^.^|伤害减免(DR)% ^.^|需求

^.^|龙岩靴(镀金)
^.^|6%
^.^|60级防御

^.^|符文靴(镀金)
^.^|5%
^.^|40级防御
|===

=== 戒指

[%autowidth]
|===
^.^|物品 ^.^|加成

^.^|沙尘暴戒指
^.^|对于近战来说，这将带来稳定的DPS提升，在使用足够多其他技能的增益效果后，其威力会下降。

^.^|钻石银戒指
^.^|1% DR

^.^|Aorpheat的图章戒指
^.^|有5%的几率使精英宝箱翻倍，并获得额外100%的金钱。

^.^|富贵戒指
^.^|有7%的几率使精英宝箱翻倍。

^.^|剑刃回响之戒
^.^|强大的近战DPS提升，但每次攻击需要更多的祝祭和药水。

^.^|灵魂之力戒指
^.^|强大的魔法DPS提升，不影响古代魔法。
|===

== 结论

在辅助技能方面投入最少努力的顺序如下：

- 获取**落日刺剑**，
- 获取**沙尘暴戒指**，
- 以近战方式完成100次**熔岩洞窟**，
- 使用**Slicing Winds**完成其余的**熔岩洞窟**。
