= 冒险模式/指南

== 前言

冒险模式将颠覆你对梅尔沃的了解！你一开始只能解锁近战战斗，必须通过支付逐渐增加的金币费用来解锁各个技能。这意味着你选择的技能将极大地影响你在游戏中的道路。你的非战斗技能将受到你的战斗等级的限制，因此一开始你可以进行的技能训练非常有限。

这个模式要求你比其他模式更多地进行战斗，尤其是在开始阶段。一方面，对于新玩家来说，不使用这些技能很难理解所有技能是如何相互关联的。另一方面，冒险模式减少了早期游戏选择的数量，这可以帮助新玩家更好地了解游戏。这都是权衡的问题！

说到权衡，这就是这个模式的核心。你可以通过选择另一项技能或瞄准不同的敌人来节省一项技能的时间，但这可能会在其他地方花费更多时间。诀窍在于选择游戏中你最喜欢的方面，并将时间和注意力集中在这些领域，然后你可以将时间缩短策略应用到你不太喜欢的领域。这都是关于权衡！我们稍后会详细讨论这个问题。尽管如此，确实有办法让你自己受到严重的限制，所以这份指南的目标是帮助你避免大的错误，将时间花在你想花的地方。

下面给出了一个大致的策略，但不是必须得！

== 开局阶段

首先，你需要进行一些基本的近战战斗，以获得一些战斗等级和现金来解锁第一个技能。在教程中，你制作了一把**青铜匕首**。直到获得钢铁武器之前，这将是你需要的最强武器。装备你的**青铜匕首**和食物**虾**，然后开始打**植物**。记得按下“拾取所有”按钮来收集打出来的土豆！使用不同的战斗风格（戳刺、劈砍、格挡）以保持技能的大致平衡。

在技能大约到 10|10|10（攻击、力量、防御）之后，尝试开始刷**奶牛**。如果感觉太厉害，可以回去再多刷一会**植物**。

之后，按照 https://wiki.melvoridle.com/w/HCCO/Guide[HCCO/指南(硬核+仅使用战斗技能+不使用非战斗技能+12个格子),window=_blank] 的建议来平稳地提升敌人的难度，但请注意，有些怪物需要你先解锁**屠杀者**技能。请注意，这个指南可能有点过时，所以下面我会提到一些基本的变化。

=== 前期赚钱

你的第一个赚钱方法就是刷**奶牛**。收集它们的**皮革**，然后去商店尽可能多的换成**绿龙皮**，然后卖掉。这会比直接出售**皮革**多赚**50**个金币。

从经验上看，**财宝护符**是这种模式中的重要升级，但由于扒窃技能的更新和战斗战利品箱的扩展，这可以成为你早期的主要赚钱方式（在开始角色后的几个小时内）。我将在下面讨论更高级的策略（相对于男性角色，可以在4-6小时内达到自动攻击女性角色，而不是8小时以上），但如果你只是从男人身上进行盗窃，最终你将达到100%的成功率，并能够在不损失食物的情况下自动攻击他。在成功率约为93%之前，你将不得不手动进食，以防止在这个阶段死亡。

=== 提前规划

==== 技能解锁消耗

解锁技能的成本会飞速增加，因此规划出技能解锁顺序非常重要。以下是解锁所需成本：

[%autowidth]
|===
|解锁数量 |花费 |累计花费
|1 | 10,000	| 10,000
|2 | 25,000	| 35,000
|3 | 50,000	| 85,000
|4 | 200,000	| 285,000
|5 | 250,000	| 535,000
|6 | 400,000	| 935,000
|7 | 1,000,000	| 1,935,000
|8 | 2,500,000	| 4,435,000
|9 | 10,000,000	| 14,435,000
|10 | 25,000,000	| 39,435,000
|11 | 50,000,000	| 89,435,000
|12 | 100,000,000	| 189,435,000
|13 | 200,000,000	| 389,435,000
|14 | 500,000,000	| 889,435,000
|15 | 500,000,000	| 1,389,435,000
|16 | 500,000,000	| 1,889,435,000
|17 | 500,000,000	| 2,389,435,000
|18 | 500,000,000	| 2,889,435,000
|19 | 500,000,000	| 3,389,435,000
|20 | 500,000,000	| 3,889,435,000
|21 | 500,000,000	| 4,389,435,000
|22 | 500,000,000	| 4,889,435,000
|===

====  战斗等级

请阅读有关战斗等级的维基页面。

你的非战斗技能受制于你的战斗等级，这极大地限制了你可以做的事情。在这个模式中，达到99级的战斗等级是一个重要的早期目标。战斗等级考虑了生命值、防御、祝祭，以及你的最高战斗风格：魔法、远程或攻击/力量。通过攻击和力量来获得99级的战斗等级会更容易。

战斗等级的计算公式告诉我们，如果你在一个战斗风格中的等级很高，那么选择另一个战斗风格不会提高你的战斗等级，直到你超过另一个战斗风格的等级。

因为近战比其他方式更容易达到99级的战斗等级，祝祭还可以进一步加速这一进程。你将会要在技能（攻击、力量、防御、生命值、祝祭）大约在79/79/76/78/75左右，达到你的目标，尽管你可以随意调整这些数字，它们非常灵活。

==== 长期目标

如果你想完成冒险模式，你将需要数十亿的金币。要获得这么多钱，你需要一个好的方法和一个赚钱计划。

请阅读**赚钱指南**，以制定你的赚钱进程草案。

例如：

* 解锁烹饪。
* 杀牛并烹饪牛肉。
* 解锁盗窃。
* 将你的战斗等级提升到30。
* 从男人身上进行扒窃，通过手动进食牛肉来维持HP。
* 逐渐获得扒窃加成的物品-从强盗或劫匪那里获得盗贼斗篷、从戈耳宾首领那里获得戈耳宾面具、从随便一个NPC那里获得潜行靴。
* 解锁制作**翡翠弩箭**所需的技能（注意：有几种在游戏后期以及大后期可行的赚钱方案。翡翠弩箭目前是最强的后期赚钱方法。首先专注于提高全局加成，因为它们可以对任何赚钱的方法提供加成）。

==  技能解锁顺序

选择技能顺序将很大程度地改变你在冒险模式中的玩法。
许多技能都相互关联，因此你将受到你的战斗等级和你无法获得的物品的限制。

如果你的目标是100%的完成度，那么关键是尽快获得最佳的赚钱方法。
这一部分提供了从零开始到使用一些游戏中最好的方法赚钱的路线。

===  例子: 扒窃

解锁路线：烹饪 > 屠杀者 > 钓鱼 > 扒窃 > 采矿 > 锻造 > 祝祭 > 战斗等级 99

杀植物刷土豆。当你有100个土豆时，切换到杀奶牛。

杀奶牛，拾取所有物品，包括皮革，然后购买绿龙皮，然后出售它。

解锁烹饪，停止食用土豆。改为食用牛肉。

解锁屠杀者，从木乃伊那里获得力量护符和绿宝石金戒指。

解锁钓鱼。这将成为烹饪原料的来源。

出售鱼来解锁扒窃。

要决定在扒窃中选择哪个目标以获得最多的金钱并不容易。使用 https://docs.google.com/spreadsheets/d/1caJNSMYi6fjqEpSe3vhU4MXgqimAy8JePyk-NqXoKjY[扒窃计算器] 来决定选择谁。请记住，在早期游戏中的结果与表格上所给的结果差异很大 - 你需要复制表格并输入你当前的情况。

解锁采矿和锻造。有了它们，你可以制作自己的盔甲和武器。

过渡到秘银装备，然后是精金装备。将你得到的盔甲镀金。

之后，你可能想要达到战斗等级99，来提升你的扒窃加成。为此，解锁祝祭并一起提升近战技能和祝祭技能。使用你拥有的消耗最高和最有用的祝祭。骑士精神和虔诚是提升祝祭的最佳选择：消耗更少祷告点的选项具有较低的祝祭点数-每点祝祭经验值，会减缓你的战斗速度。

提升你的战斗等级。
与以下怪物战斗：

* 攻击等级1-9：奶牛。
* 攻击等级10-49：冰冻弓箭手。
* 攻击等级50-99：巨型螃蟹。

你可以查看战斗模拟器，以了解哪种怪物适合你的情况。不要忘记考虑食物消耗。

以战斗等级99为例，以下组合足够了：攻击77，力量75，防御79，生命值77，祝祭91。

对扒窃后期赚钱提供加成的技能包括草药学、灵巧和召唤。由你决定以何种顺序解锁它们以及它们所需的其他技能。 https://docs.google.com/spreadsheets/d/1caJNSMYi6fjqEpSe3vhU4MXgqimAy8JePyk-NqXoKjY[扒窃计算器,window=_blank] 将有助于比较这些改进。

=== 例子: 龙岩标枪

解锁路线：烹饪 > 屠杀者 > 钓鱼 > 采矿 > 锻造 > 符文锻造 > 生活类魔法 > 祝祭 > 战斗等级 99 > 伐木 > 弓匠。

大部分事情与示例中的方式相同，但我们没有解锁盗窃，而是使用生活类魔法来获取祝祭点数。

在解锁锻造之后，解锁符文锻造、生活类魔法和祝祭。

通过生活类魔法的祝福祭品来获取祷告点数。

将你的战斗等级提升到99级。

解锁伐木和弓匠。

提升已解锁的技能以开始通过龙岩标枪赚钱。

==  技能的优缺点

建议在游戏下面这些阶段，分别解锁这些技能：

* 早期游戏：技能解锁1-3个。
* 中期游戏：4-8。
* 晚期游戏：9-13。
* 末期游戏：14-18。

=== 攻击、力量

优点：在游戏开始时就解锁。不需要弹药来训练。可以快速获得起始武器/护甲。在游戏开始阶段需要使用它一段时间。通过蛮族手套钓鱼，可以在挂机时训练力量。对抗远程敌人有优势。

缺点：在晚期游戏中不如魔法强大。需要训练两种技能而不是一种。对魔法敌人较弱。

=== 防御

优点：在游戏开始时解锁。可以与任何类型的战斗训练。始终有助于战斗等级。减少食物消耗。

缺点：不会增加你的伤害。

=== 远程

优点：从敌人那里获得武器/护甲掉落相对容易。冰冻箭头强大，用近战武器相对迅速获得。对抗魔法敌人有优势。

缺点：需要收集弹药，如果没有采矿+锻造来制作弩箭/飞到，以及伐木+制箭来制作箭矢，速度会慢得多。不如其他形式的战斗用处大。在晚期游戏中不如魔法强大。对抗近战敌人不利，大多数敌人都是近战的。

建议解锁时间：晚期游戏，当与水神地牢战斗时。

=== 魔法

优点：非常强大，尤其是在末期游戏中。古代魔法伤害高且准确度极高。对抗近战敌人有优势，大多数敌人都是近战的。生活类魔法让你轻松获得祝祭点数，还有一些挂机经验。可以轻松用符文制作好的武器/护甲。

缺点：需要先解锁采矿+符文锻造才能开始。制作符文需要时间，最好的符文需要高符文锻造等级。你需要伐木或扒窃来制作元素法杖，否则它们只能从怪物掉落。祝祭点数也可以通过钓鱼获得。需要古代魔法才能充分发挥潜力。对抗远程敌人不利。

建议解锁时间：中晚期游戏，当你已经解锁了采矿和符文锻造时。

=== 祝祭

优点：在战斗中非常有帮助，特别是在困难的战斗或晚期游戏中。你可以从所有怪物处获得骨头。始终有助于战斗等级。

缺点：需要一定的祝祭点数供应，骨头掉落比较少。最好的获得祝祭点数的方式是从钓鱼获得的生骷髅鱼或从生活类魔法获得的祝福祭品。

建议解锁时间：中期游戏，当你有一个良好的祝祭点数获取来源时。

=== 屠杀者

优点：重新选择简单的屠杀者任务是免费的，所以你总是可以从你想要战斗的任务中获得屠杀者硬币和经验值。屠杀者硬币可以用于购买升级和补给品，提供食物、骨头和弹药。屠杀者区域有重要的敌人，比如木乃伊，可以获得绿宝石金戒指和黄宝石金戒指。

缺点：获取屠杀者硬币并且需要你手动重新选择任务，或者至少切换到你当前的任务，对于大多数挂机玩家来说，直到你获得150k屠杀者硬币以购买自动切换目标之后才能挂机，这很不方便。你仍然可以通过在屠杀者区域战斗来获得一些屠杀者经验。需要一段时间来赚足够的硬币来购买任何东西。不会提高战斗等级。

建议解锁时间：早期到中期游戏，当你需要从屠杀者敌人那里获得掉落物品时。

=== 伐木

优点：容易挂机，高级别时每小时获得的金币也不少。获得用于制作魔法法杖和箭矢的木材。鸟巢是获得种子的不错来源。需要99级以有效地制作龙岩标枪，这是末期游戏最佳赚钱策略之一。

缺点：你可以从扒窃中获得伐木能得到的一切，而且每小时获得金币比宝石手套差，直到达到高级别。

建议解锁时间：晚期到末期游戏，当你计划制作龙岩标枪时。

=== 钓鱼

优点：与烹饪一起，它是一个容易挂机的食物供应。可以获得用于经验值的古代技能戒指或解锁生骷髅鱼的瓶中信 - 这是获得祝祭点数的绝佳来源。可以用蛮族手套挂机训练力量。在高级别时，离线赚的钱也不少。不强制要求通过烹饪来从钓鱼获得可食用的食物，因为有生魔法鱼，但与烹饪相比，速度非常慢。

缺点：你可以从农务或战斗中获得食物。祝祭点数可以通过生活类魔法获得。每小时获得金币在高级别之前不如宝石手套。

建议解锁时间：早期到晚期游戏，具体取决于你的食物/祝祭点数是否来自这里或来自农务和生活类魔法。

=== 生火

优点：技能斗篷会给你经验奖励，但只有在达到99级时才能购买。通过生火给烹饪提供经验奖励。如果你要达到最大的完成度，可能希望在练其他技能之前获得生火斗篷和生火宠物。

缺点：需要99战斗等级才能获得技能斗篷，它的吸引力受到晚期获得的限制。需要从伐木中获取木材。需要草药学以制作有效的恒温药水来进行训练。

建议解锁时间：晚期到末期游戏，当你拥有伐木和草药学，并希望为了经验奖励而进行生火技能斗篷的刻苦训练。

=== 烹饪

优点：与钓鱼一起，可以轻松快速地获得食物。如果你不能积极玩游戏，从收集怪物掉落或农务中获得食物会很困难。

缺点：你可以从农务或战斗中获得食物和很多其他物品。农务可以提供食物，而不需要经常按“全部拾取”按钮。除了食物外，不提供任何优势。

建议解锁时间：取决于你是否参与钓鱼和是否推迟农务。

=== 采矿

优点：使用宝石手套进行采矿是早期最佳的赚钱策略，而且是可以挂机的。在获得宝石手套之前可以获得一些离线金币。需要符文精华用于符文锻造和奇怪的粘液用于农务。通过锻造，你可以获得制作护甲装饰、近战护甲和武器，以及远程弹药所需的金属锭。需要创建龙岩标枪。

缺点：需要500k金币购买第一双宝石手套。

建议解锁时间：早期游戏 - 宝石手套是爱，宝石手套是生活。

=== 锻造

优点：在购买宝石手套之前，制作银/金锭用于护甲升级和金币。制作远程弹药。制作近战武器/护甲。需要制作护甲，以便在一些关键的末期游戏地点进行挂机。需要创建龙岩标枪。

缺点：你可以在解锁锻造之前杀死骑士以获得近战武器/护甲（除手套外）。虽然锻造速度更快，但你可以从怪物掉落中获得金锭和银锭。可以从怪物掉落中获得远程弹药。

建议解锁时间：当你想要更好的近战装备时。

=== 扒窃

优点：在获得其他材料（如食物、木材和矿石）的同时，可以获得不错的金币/小时。扒窃农夫是种子的最佳来源。可以获得黑色礼帽，以从战斗中获得更多掉落物品。

缺点：难以开始。你可以从其他地方获得必要的东西。

建议解锁时间：中期到晚期游戏，具体取决于你认为这些掉落物品何时会有用。

=== 农务

优点：获得食物，无需游戏内时间。获得制作草药学所需的各种草药。获得大多数类型的木材。如果出售草药/木材，可以获得一些不错的金币，而无需游戏内时间。

缺点：需要定期打开游戏以获得最多的食物。从扒窃、战斗或伐木中获得种子。需要购买堆肥或杀死农民获得。需要采矿来获得最佳的经验和食物产量。扒窃或伐木是获得胡萝卜种子所需的。

建议解锁时间：早期到晚期游戏，具体取决于你是否首先进行钓鱼和烹饪。

=== 弓匠

优点：需要制作远程战斗的箭矢和弓。需要制作龙岩标枪。

缺点：远程不是最强的战斗风格，你可以从战斗掉落中获得大多数箭矢和弓。以高级别为前提的赚钱制作龙岩标枪。

建议解锁时间：晚期到末期游戏，当你开始制作龙岩标枪时。

=== 制造

优点：制作远程护甲和珠宝。

缺点：远程护甲和珠宝可以从战斗中掉落。不是一个有用的技能。

建议解锁时间：末期游戏，当你没有其他东西可以解锁时。

=== 符文锻造

优点：让你使用魔法。还需要用于获得祝祭点数的生活类魔法。诅咒和光环会让你变得更强大，直到你成为一个具有古代魔法的行走DPS机器。

缺点：需要先获得采矿。在解锁魔法之前什么也不能做。更高级别的符文需要高级别，这意味着高级别的战斗。

建议解锁时间：中期到晚期游戏，当你计划开始训练魔法时。

=== 草药学

优点：提高其他技能的效率。战斗药水提供了一种提升，但在晚期战斗中，渴望使用钻石运势药水 IV 和伤害减免药水 IV。等级53有助于更快地制作龙岩标枪。

缺点：需要从农务中获得草药，一些次要材料根据你的可用技能而难以获得。需要高级别的战斗等级和大量的材料才能获得最佳战斗药水。训练速度较慢。

建议解锁时间：中期到晚期游戏，当你有大量草药并希望提高其他技能的效率时。

=== 灵巧

优点：为其他技能提供小幅度的加成，增加经验、专精、资源留存、战斗增益等。在较高级别时，提供了轻松的挂机方式，可以获得不错的金币/小时。

缺点：许多障碍需要你还没有解锁的技能或物品。障碍变得越来越昂贵，有些会有较大的减益效果。除非你有Aorpheat的图章戒指，否则金币/小时在高级别之前不会超过宝石手套。

建议解锁时间：中期到末期游戏，当你有足够的金钱、技能和物品来创建一个有用的课程时。

=== 召唤

优点：为其他技能提供小幅度的提升，并在战斗中有所帮助。一些连携效应提供了大幅度的加成。

缺点：需要解锁更多的印记和连携效果，需要解锁其他技能。获取某些符文的材料可能会有些棘手，而且碎片很贵。需要完成一门灵巧课程，并花费屠杀者硬币购买装备来进行高效训练。

建议解锁时间：末期到游戏尾声，当你有足够的技能来解锁有用的召唤兽，并有足够的金钱来购买碎片时。

=== 星象学

优点：为所有技能提供加成。无需训练的要求。

缺点：这些奖励不会帮你赚取下一个技能所需的金币。

建议解锁时间：末期到末期游戏，当你已解锁了最佳的赚钱方法之一。
