= 大地之神地牢-指南

https://wiki.melvoridle.com/w/Earth_God_Dungeon/Guide[原文地址,window=_blank]

== 装备

由于战斗三角，建议用魔法通关地神地牢，因为这里的敌人大多是近人，包括最终的BOSS特兰。

当敌人击中你时被眩晕会使你受到30%的额外伤害。 这里的想法是，如果你受到特兰的减速（+33%的攻击间隔）的影响，那么你可以比他更快地摆脱特兰的眩晕效果。 攻击间隔2.9秒的武器会及时逃脱，但攻击间隔3.0秒的武器不会没有间隔减少加成；具体来说，3.0秒的间隔武器需要减少到2.9秒或更快。 因此，只有在此时使用迸发I或迸发II时使用云爆法杖才是安全的。

在保持适当通关时间的同时，最安全的咒语可能是20k精准必中的飓风，配备魔杖和盾牌。

值得注意的是，使用云爆法杖，即使使用迸发I或迸发II，也可能远远超过任何其他法术/武器组合。 然而，请注意，这将花费大量符文，用完符文将使你面临死亡的危险。 查看战斗模拟，看看你每小时将花费多少符文，并制作大量额外的符文以维持必要的挂机时间。

以下方法将充分减少你的间隔，以避免在迸发光环上花费空气符文，使这种特殊的方法有效地万无一失。 如果您满足其中一个或多个要求，您可以使用狂怒II光环来更好地提高通关时间。

* 拥有Otto宠物
* 在被动槽中佩戴上古之冠或沙地靴
* 购买星象学中阿斯塔的5级20级专精(-5%攻击间隔)

您使用的任何装备都需要与 https://wiki.melvoridle.com/w/Combat_Simulator[战斗模拟器,window=_blank] 进行检查，以确保其对您的有效性。

[%autowidth]
|===
|部位 |物品 |伤害减免
|头盔|格拉西娅神灵头盔|8%
|护甲|格拉西娅神灵胸甲|8%
|护腿|格拉西娅神灵胫甲|8%
|靴子|格拉西娅神灵靴|8%
|手套|格拉西娅神灵手套|8%
|斗篷|骷髅斗篷|3%
|项链|精英魔法护符|2%
|戒指|术士戒指|
|武器|魔杖(强力)|
|护盾|鳞盾|8%
2+|总计|53%
|===

检查你是否可以使用 https://wiki.melvoridle.com/w/Combat_Simulator[战斗模拟器,window=_blank] 挂机地牢可能会很有帮助。
https://consolelog.gitee.io/caniidle/[我能挂机吗,window=_blank] 可能会误导您所需的DR数量。 ”如果你使用杖的攻击间隔为2.9或更低，或者如果你使用魔杖，你可以取消选中状态伤害复选框，因为你不会受到这些敌人的眩晕伤害。

如果你没有足够的伤害减免，可以使用钻石银戒指、炼狱斗篷和龙焰盾牌。

如果你没有术士戒指，可以使用富贵戒指或Aorpheat的图章戒指，但调整后的掉落时间会更糟。

元素圣斗士之怒是好的，但不是强制性的。

如果你有未使用的流水宝箱，你可能想打开它们来获得魔杖（精英）。

== 最大化farm效率

本指南的其余部分不适用于您的首次通关、平均通关，甚至前100次。
这纯粹是为了最大效率地刷卷轴以及其它丢失的物品。
这将假设所有技能为99，可以获得游戏中几乎所有的武器和物品，并可以获得所有伤害减免以及生命值宠物。
这假设你（除非另有说明）正在使用最佳灵巧设置，正在使用你最好的dps祝祭，你最好的召唤连携作用，并且正在使用钻石运势药水

== 魔法

这个build使用了水之迸发或水之波（符文成本略有降低）、苦痛III和狂怒II。

要使用此方法，您需要具有2.9或更低的攻击间隔。这是在与Otto的最终游戏中最容易实现的，或者使用迸发I或迸发II。

这可以实现每小时刷26到27张卷轴，这稍微取决于你的星象学加成。

*消耗品*:

* 钻石运势药水
* 战斗之心(95级祝祭)和全知(91级祝祭)
* 龙与女巫
* 巫师卷轴
* 水之迸发，苦痛III和狂怒II

[%autowidth]
|===
|部位 |物品 |伤害减免
|头盔|屠杀者巫师帽(大师)|
|护甲|格拉西娅神灵胸甲|8%
|护腿|格拉西娅神灵胫甲|8%
|靴子|格拉西娅神灵靴|8%
|手套|格拉西娅神灵手套|8%
|斗篷|骷髅斗篷|3%
|项链|元素圣斗士之怒|3%
|戒指|富贵戒指|
|武器|云爆法杖|
|被动|黑色礼帽|
2+|总计|44%
|===


