= 大气之神地牢-指南

== 为什么刷大气之神地牢?

* 解锁商店中的 永恒疾速技能(-15%制造和弓匠间隔)，大幅度提高制造和弓匠的速度。
* 阿里亚斯神灵套装，远程的重要升级。 对挂机流水之神地牢是必要的。
10个阿里亚斯神灵手套可以用来升级到剧毒手套。

* 死射护符 — 远程的重要升级.
* 死射戒指 — 远程的重要升级。10个可以升级成剧毒戒指。
* 阿里亚斯神剑 — 花两个小时来替换炼狱爪。需要5个来升级创世神剑。

根据 https://github.com/hm0809/MelvorProbDist/blob/main/main.py[模拟器1,window=_blank]和 https://github.com/vbion/melvor-coupon-solver/[模拟器2,window=_blank] :

* 平均需要刷69次地牢才能获得完整的阿里亚斯盔甲。（1）
* 如果你想要完整的护甲套装，那么你需要刷91次才有75%的几率达成，或者192次才有95%的几率。（2）
* 如果你想要全套和风暴弓，那么75%是277次，95%是576次。

== 挂机装备

由于战斗三角的关系，建议用近战击败空神地牢，因为这里的敌人是远程和近战。

以下build可以在生命值达到90级（龙焰之盾的生命值为+30，总生命值为930）的要求下安全的挂机地牢，这同时适用于标准、硬核和冒险游戏模式。
用战斗模拟器或 https://consolelog.gitee.io/caniidle/[我能挂机吗,window=_blank] 来检查你自己的设置，以确保你不会死。
虽然阿里亚斯的标准攻击高于你的自动进食阈值，但它永远不会使用标准攻击，因为它有100%的机会使用四种特殊攻击中的一种。

[%autowidth]
|===
|部位 |物品 |伤害减免
|头盔|古代头盔(镀金)|7%
|护甲|古代胸甲(镀金)|7%
|护腿|古代胫甲(镀金)|7%
|靴子|龙岩靴(镀金)|6%
|手套|古代龙皮护腕(升级)|6%
|斗篷|烈焰斗篷|4%
|项链|精英防御护符|2%
|戒指|沙尘暴戒指|0%
|宝石|精准宝石|0%
|盾牌|龙焰盾牌|8%
2+|总计|47%
|===


有了更多的生命值，你可以开始将伤害减免属性换成物品翻倍几率和普通DPS，例如，在相同的build中，在1090的生命值贵，你可以装备一个黑斗篷和一个精英荣耀护符。

同样值得注意的是，可以在较低的生命值下手动通关地牢，并装备由此产生的靴子和手套，使其更早开始挂机。

沙尘暴戒指非常强大，如果你没有额外buff，它会提高你的通关速度。
然而，请注意，如果有足够多的额外近战等级、更好的装备或灵巧、星象学、草药学、召唤或祝祭的buff，沙尘暴戒指实际上可能会影响你通关地牢的速度。

有两种可选戒指可以替代:

* Aorpheat的图章戒指或者是富贵戒指:
** 增加你在地牢完成时获得的副本卷轴和宝箱的数量
* 剑刃回响之戒:
** 以消耗品增加为代价，大幅增加武器DPS

=== 武器选择

该表绘制了一些战斗模拟器的结果，这些结果根据生产所有所需消耗品所需的时间进行了调整，并对每项技能的确切加成进行了一些假设。

您可以在此处查看电子表格。制作一个副本来定制资源值以匹配您自己的值，每个表上还有一列允许您输入自己的模拟人生结果。（https://docs.google.com/spreadsheets/d/1JAuROH4I_dNph9VwBXx7ffoGnWcoHlbsW0doWMBIPU0/edit?usp=sharing[链接,window=_blank]）

[%autowidth]
|===
|武器|调整后每小时卷轴数量|每小时卷轴数量|对比龙岩剑
|龙岩剑 | 1.45 | 1.45+ | 100%
|龙爪 | 1.62 | 5.4+ | 370%
|落日刺剑 | 1.83 | 7.3+ | 500%
|古代之爪 | 1.86 | 8.0+ | 544%
|炼狱爪 | 1.9 | 9+ | 610%+
|===

通常的食物消耗是每小时150k到200k生命值。

理想情况下，你需要从炼狱要塞获得10个炼狱核心，并刷出龙爪和古爪制作成炼狱爪。
查看 xref:./炼狱要塞-指南.adoc[炼狱要塞-指南]，以便效率地farm它。
你应该能够挂机刷到里面的所有怪了，除了BOSS。

== 最大效率farm

本指南的其余部分不适用于您的首次通关、平均通关，甚至前100次。
这纯粹是为了最大效率地刷卷轴以及其它丢失的物品。
这将假设所有技能为99，可以获得游戏中几乎所有的武器和物品，并可以获得所有伤害减免以及生命值宠物。
这假设你（除非另有说明）正在使用最佳灵巧设置，正在使用你最好的dps祝祭，你最好的召唤连携作用，并且正在使用钻石运势药水

=== 近战

这个时钟大约每小时32个卷轴，这取决于你的星象学加成。
因为这个版本使用了老罗大斧，可以获得+100%战斗物品翻倍，所以不需要任何额外的翻倍属性，所以这个build可以无损最大化dps！

*消耗品*：

[%autowidth]
|===
|部位 2+^.^|物品(最佳->其次)
|头盔|拉格纳神灵头盔|
|护甲|拉格纳神灵胸甲|
|护腿|拉格纳神灵胫甲|
|靴子|拉格纳神灵靴|
|手套|无情狂怒手套|拉格纳神灵手套
|斗篷|极限技能斗篷|古代炼狱斗篷
|护符|元素圣斗士之怒|斗士护符
|戒指|剑刃回响之戒|
|宝石|迅捷宝石|
|武器|老罗大斧|
|被动|海盗钩|斗士护符
|消耗品|磨刀石|怪物猎人卷轴
|===

