= 流水之神地牢-指南

https://wiki.melvoridle.com/w/Water_God_Dungeon/Guide[原文地址,window=_blank]

== 为什么刷流水之神地牢?

* 商店中的博学多识技能 - 大大加快符文锻造和草药学。
* 格拉西娅神灵套装 - 魔法最佳装备。强制挂机大地之神地牢。你需要10个手套才能升级为癫狂灼烧手套。
* 云爆法杖 - 游戏中魔法最好的DPS武器之一。
* 术士护符 - 减少你的食物消耗。
* 术士戒指 - 巨额的伤害提升，你需要10个才能升级到癫狂灼烧戒指。
* 5个格拉西娅神剑，升级为创世神剑。

根据 https://github.com/vbion/melvor-coupon-solver/[模拟器]:

* 如果你想要完整的护甲套装，那么你需要刷地牢91次才有75%的几率，或者192次才有95%的几率。
* 如果你想要全套和云爆法杖，那么75%是277次，95%是576次。

== 装备

由于战斗三角，建议用远程风格来刷水神地牢，因为敌人使用魔法和近战。

[%autowidth]
|===
|部位 |物品 |伤害减免
|头盔|阿里亚斯神灵头盔|8%
|护甲|阿里亚斯神灵胸甲|8%
|护腿|阿里亚斯神灵胫甲|8%
|靴子|阿里亚斯神灵靴|8%
|手套|阿里亚斯神灵手套|8%
|斗篷|炼狱斗篷|4%
|项链|精英远程护符|1%
|戒指|富贵戒指|
|武器|古代十字弩|
|护盾|鳞盾|8%
|弹药|绿宝石弩箭|
2+|总计|53%
|===

使用 https://consolelog.gitee.io/caniidle/[我能挂机吗,window=_blank] 或 https://wiki.melvoridle.com/w/Combat_Simulator[战斗模拟器,window=_blank] 检查您自己的设置，看看您是否满足HP要求。

财富戒指或Aorpheat的图章戒指是获得翻倍战利品的首选，但如有必要，您可以使用钻石银戒指获得1%的DR。

如果你有元素圣斗士之怒，那就使用它，但它不是强制性的。

因为地牢中后期的怪物闪避非常高，所以古代十字弩可以显著加快通关时间，因为它可以降低敌人的躲避能力，直到战斗结束。

鳞盾很重要，因为毒伤是百分比伤害，这意味着格拉西娅会受到极大的伤害。

使用鳞盾，与未升级版本的古代龙皮护盾(升级)相比，你通关地牢的速度至少快10%。

使用绿宝石弩箭将您的钻石制作为钻石运势药水IV。

根据你的情况，使用前两个祝祭词条的准确性或最大命中率。 用 https://wiki.melvoridle.com/w/Combat_Simulator[战斗模拟器,window=_blank] 核实，看看哪一个更能降低你的挂机时间。

=== 最大化farm效率

本指南的其余部分不适用于您的首次通关、平均通关，甚至前100次通关。 这纯粹是为了最大化刷卷轴以及其它丢失的物品。 这将假设所有技能为99，可以获得游戏中几乎所有的武器和物品，并可以获得所有伤害减免以及生命值宠物。 这假设你（除非另有说明）正在使用最佳灵巧设置，正在使用你最好的dps祝祭，你最好的召唤连携作用，并且正在使用钻石运势药水

=== 远程

普拉特斗篷比极限技能斗篷略快，但由于它使你弹药消耗变成两倍多，所以不推荐使用。

此时大约每小时能刷19到21次卷轴，这取决于你的星象学加成

*消耗品*：

* 钻石运势药水
* 战斗之心(95级祝祭)和缜密(87级祝祭)
* 龙与半人马
* 翡翠弩箭

[%autowidth]
|===
|部位 |物品 |伤害减免
|头盔|屠杀者头盔(大师)|6%
|护甲|屠杀者胸甲(大师)|6%
|护腿|阿里亚斯神灵胫甲|8%
|靴子|阿里亚斯神灵靴|8%
|手套|阿里亚斯神灵手套|8%
|斗篷|极限技能斗篷|
|护符|死射护符|
|戒指|富贵戒指|
|武器|震荡波|
|盾牌|远程之盾|9%
|被动|黑色礼帽|
2+|总计|45%
|===

=== 魔法

此构建使用了炎之迸发、苦痛III和迸发II咒语。

要使用此方法，你需要拥有1090点生命值和57点伤害减免。这是通过使用崎岖水域而不是湖中游泳来实现的。任何其他方法都可以让你在阿里亚斯的伤害中幸存下来，但会让你损失超过3%的伤害。

此时大概是每小时刷19到21个卷轴，这取决于你对魔法之盾的获取，也稍微取决于你的星象学加成。值得注意的是，运行这个build需要更长的时间，因为创建所有必要符文的时间可能比收集弹药的时间更长。这个版本还需要近战之盾能够生存并保持dps。因此，它的整体效果比远程对应的效果差一点。

*消耗品*:

* 钻石运势药水
* 战斗之心(95级祝祭)和全知(91级祝祭)
* 龙与女巫
* 巫师卷轴
* 炎之迸发、苦痛III和迸发II咒语

[%autowidth]
|===
|部位 |物品 |伤害减免
|头盔|格拉西娅神灵头盔|8%
|护甲|格拉西娅神灵胸甲|8%
|护腿|格拉西娅神灵胫甲|8%
|靴子|格拉西娅神灵靴|8%
|手套|格拉西娅神灵手套|8%
|斗篷|骷髅斗篷|3%
|项链|元素圣斗士之怒|3%
|戒指|富贵戒指|
|武器|海之歌|
|盾牌|魔法之盾|9%
|被动|黑色礼帽|
2+|总计|55%
|===


