= 炼狱要塞-指南
:stem:

== 为什么刷炼狱要塞？

对于炼狱要塞，主要有三个目标：

* 在100个熔岩洞窟后通关一次，可以获得具有4%伤害减免的地狱之角。
* 刷10次，可以获得10个炼狱核心，用于将龙爪和古代爪合并为地狱爪。
* 多次刷该副本可以赚取大量金钱。在游戏本体临近结束的时候可以这么做。

== 手动进食的Build

以下Build适用于刚完成熔岩洞窟以及刷出接下来的古代之爪的玩家。

如果不手动进食，该Build是无法挂机的，主要死亡原因是BOSS马尔克斯的组合技——封印（眩晕）+穿透爪。

[%autowidth]
|===
^.^|部位 ^.^|物品 ^.^|伤害减免(DR)%

^.^|头部
^.^|古代头盔(镀金)
^.^|7%

^.^|躯干
^.^|古代胸甲(镀金)
^.^|7%

^.^|裤子
^.^|古代胫甲(镀金)
^.^|7%

^.^|足部
^.^|龙岩靴(镀金)
^.^|6%

^.^|手套
^.^|古代龙皮护腕(升级)
^.^|6%

^.^|斗篷
^.^|火焰斗篷
^.^|2%

^.^|脖颈
^.^|精英防御护符
^.^|2%

^.^|戒指
^.^|沙尘暴戒指
^.^|0%

^.^|武器
^.^|古代之爪
^.^|0%

^.^|副手
^.^|古代盾牌(镀金)
^.^|7%

2+^.^|总计
^.^|44%
|===

强烈建议使用古代之爪，次选是落日刺剑，因为您想要快速摆脱眩晕状态，攻击速度越快，您就越快做到这一点。

您可能需要使用祝祭来提高准确率。没有祝祭，您对BOSS的命中率大概只有25%。有了祝祭，大约是40%。

如果您有钻石运势药水，现在就是使用它们的合适时机了。

在第一次通关该副本后，你会获得炼狱斗篷，这回让你在接下来9次副本的过程更容易，如果您目标是炼狱之爪的话。

可选择的是，建议获得龙焰盾牌，最好是带上冰瀑咒语和女巫召唤，因为它可以一击必杀绿龙，否则的话就用20k-准确度的Slicing Winds。龙焰盾牌会增加与BOSS战斗时的容错率。

如果您因为伤害减免不够而害怕，也可以将沙暴戒指换成钻石银戒指，但这会大大降低您的效率。

===	BOSS的连招

在尝试炼狱要塞时，强烈建议在未被眩晕时将自动进食阈值设置在所有BOSS的招式之上。上面的Build可以在900血量时做到这一点，但如果您不确定，建议使用战斗模拟器进行检查。另外，如果使用龙焰盾牌和990总HP，您绝对可以做到这一点。

否则的话，您需要跟踪许多BOSS技能，这很可能会导致死亡和丢失装备，需要数百小时才能重新获得它们。

以防万一，在第一次战斗中检查您的阈值。

当BOSS 使用封印时，您需要手动进食：

* _封印+穿透爪_：如果您低估了它，它将成为您的死因。请注意，在您按下键盘按钮后，自动进食有延迟，所以请在穿透爪击中您之前按下它。另外，两次伤害之间的间隔不到半秒，因此请使用自动进食以确保安全。通过以下公式计算穿透爪的伤害：

[stem]
++++
\text{640} \times \text{(1-DR)} \times \text{1.3} \times \text{2}
++++

* 封印+尾鞭：恢复满HP。如果您有时间，查看您被眩晕时尾鞭的最大伤害是多少，这样您就可以在HP允许时避免手动进食。或者您可以在战斗前通过以下公式计算它：

[stem]
++++
\text{690} \times \text{(1-DR)} \times \text{1.3}
++++

* _封印+普通攻击_：当BOSS在使用第一个封印后使用另一个封印时会发生。使用与尾鞭相同的逻辑。
* _封印+地狱火_：一张“免费出狱”卡。您根本不需要手动进食。

== 挂机选项

对于那些拥有90级生命值并完成了龙焰盾牌的玩家，只要没有用完食物，就可以提供足够的额外伤害减免，将上述Build变成仅通过自动进食就能生存的配置。

===	需求

* 祝祭 80
* 草药学 90 级，伤害减免药水达到50专精
* 召唤 65 级，女巫4级，牦牛3级

[%autowidth]
|===
^.^|部位 ^.^|物品 ^.^|伤害减免(DR)%

^.^|头部
^.^|古代头盔(镀金)
^.^|7%

^.^|躯干
^.^|古代胸甲(镀金)
^.^|7%

^.^|裤子
^.^|古代胫甲(镀金)
^.^|7%

^.^|足部
^.^|龙岩靴(镀金)
^.^|6%

^.^|手套
^.^|古代龙皮护腕(升级)
^.^|6%

^.^|斗篷
^.^|火焰斗篷
^.^|2%

^.^|脖颈
^.^|精英防御护符
^.^|2%

^.^|戒指
^.^|钻石银戒指
^.^|1%

^.^|武器
^.^|古代之爪
^.^|0%

^.^|副手
^.^|龙岩盾牌
^.^|8%

^.^|召唤1
^.^|牦牛
^.^|0%

^.^|召唤2
^.^|女巫
^.^|0%

2+^.^|总计
^.^|46%
|===

[%autowidth]
|===
^.^|加成 ^.^|类型 ^.^|伤害减免(DR)%

^.^|装备(上面)
^.^|装备
^.^|46%

^.^|守护
^.^|祝祭
^.^|1%

^.^|岩石皮肤
^.^|祝祭
^.^|3%

^.^|伤害减免药水3
^.^|草药学
^.^|6%

^.^|牦牛
^.^|召唤
^.^|1%

^.^|牦牛+女巫
^.^|召唤连携
^.^|2% 针对近战

2+^.^|总计
^.^|59%
|===

祝祭卷轴或炼金术师袋可以用来降低总消耗的祝祭点数或生存10次炼狱要塞所需的药水数量。如果已经刷了大气之神副本，可以使用阿里亚斯神灵手套和阿里亚斯神灵靴，每个额外增加2%的伤害减免。同样，在第一次清除炼狱要塞后，换成新获得的炼狱斗篷将获得另外2%的伤害减免。与+1%的防御率（来自灵巧的6级障碍湖中游泳）相结合，足够将头盔换成黑瑟礼帽，以获得10%的机会少刷一次。

== 灵巧

来自敏捷障碍的加成可以通过增加最大生命值来显著减少所需的伤害减免。

===	需求

* 攻击等级 20
* 力量 70
* 远程等级 20
* 魔法等级 20
* 烹饪等级 60
* 采矿等级 60
* 扒窃等级 80
* 灵巧等级 80

[%autowidth]
|===
^.^|种类 ^.^|部位 ^.^|生命值

^.^|岩壁平衡
^.^|障碍5
^.^|+20

^.^|崎岖水域
^.^|障碍6
^.^|+50

^.^|木筏建造
^.^|障碍8
^.^|+20

^.^|冰川跳跃
^.^|障碍9
^.^|+20

^.^|龙岩盾牌
^.^|副手
^.^|+30

2+^.^|总计
^.^|+140
|===

例如，假设与之前的90级生命值相同，在这些HP加成之后，挂机所需的防御率下降到了只有54%。 如果你足够幸运拥有猫咪芬恩，只会打91级生命值，总计1060生命值将让你的伤害减免需求降低到53%，消除了对伤害减免药水、祝祭和女巫召唤的需求。 或者与上面提到的装备改进相结合，两者都需要。 或者用于将最低生命值降低到76级生命值，尽管使用5级障碍岩壁平衡和祝祭是昂贵的。

== 在流水之神副本后

通过刷出本体游戏后期的魔法护甲的伤害减免，你现在可以利用适当的战斗三角形优势来攻克这个地牢，这意味着除了食物和符文之外，不需要消耗性资源，不需要灵巧加成，甚至是伤害减免，这样就可以多堆一些物品翻倍这个加成属性。

[%autowidth]
|===
^.^|部位 ^.^|物品 ^.^|伤害减免(DR)%

^.^|头部
^.^|黑色礼帽
^.^|0%

^.^|躯干
^.^|格拉西娅神灵胸甲
^.^|8%

^.^|裤子
^.^|格拉西娅神灵胫甲
^.^|8%

^.^|足部
^.^|格拉西娅神灵靴
^.^|8%

^.^|手套
^.^|格拉西娅神灵手套
^.^|8%

^.^|斗篷
^.^|骷髅斗篷
^.^|3%

^.^|脖颈
^.^|精英防御护符
^.^|2%

^.^|戒指
^.^|富贵戒指
^.^|0%

^.^|武器
^.^|火焰之杖
^.^|0%

^.^|副手
^.^|鳞盾
^.^|8%

2+^.^|总计
^.^|46%
|===

代替富贵戒指，可以使用Aorpheat的图章戒指；它将为你每次通关额外提供10万-15万金币，但只有5%的机会使炼狱核心掉落翻倍，对于只为了刷炼狱核心的人来说是不利的，但对于同时刷金币的人来说更好。 对于已经获得炼狱之爪、只对金币感兴趣的人，请参见赚钱指南的战斗部分。
