= 遁入迷雾

https://wiki.melvoridle.com/w/Into_the_Mist/Guide[原文地址,window=_blank]

== 副本机制

=== 痛苦的怪物

遁入迷雾的第一部分将让玩家与20个痛苦版本的165-677级随机怪物战斗，其中包括副本首领怪物。
唯一的例外是**拉格朗地龙**、**诅咒巫妖**和**幽暗水域**的怪物，所有这些都不会出现在副本中。

痛苦的怪物有正常的属性和特殊攻击，但增加了+20%*伤害减免*，并有机会应用**痛苦**减伤。

与痛苦版本的**屠杀者**怪物战斗时，**屠杀者区域**的区域效果不存在。

=== 最终Boss

在击败20个痛苦的怪物后，玩家必须击败三个boss阶段。
每个阶段都使用特定的战斗风格，只有当玩家使用相同的风格时才能被损坏。
这意味着必须从**商店**购买**副本装备交换**升级才能完成这个副本。

在每个阶段之前，战斗都会暂停，让玩家有机会阅读BOSS的特殊能力并更换他们的装备。
这意味着，例如，你不需要拥有三个单独的副本**元素圣斗士之怒**，因为你有时间在每个装备集之间交换它。
一旦玩家准备好了，他们点击一个按钮开始这个阶段。

=== 痛苦

痛苦的怪物和所有三个最后的BOSS阶段可以在他们完成攻击时应用一种特殊的状态效果，称为“痛苦”。
敌人使用的每一次攻击或特殊攻击，无论攻击是否命中或未命中玩家，都有70%的机会施加一堆痛苦，最多50堆。
命中一次以上的特殊攻击将只应用一个堆栈。

每叠加一次痛苦，玩家的最大生命值减少1%，最多50次叠加（50%最大生命值）。
至关重要的是，这也会影响玩家的自动进食阈值，使每次攻击依次变得更加危险。

怪物被击败后，或者玩家离开战斗或死亡后，痛苦堆叠会重置。

=== 手动进食

*遁入迷雾* 是游戏中第一个需要手动吃食物的副本。
虽然有一些方法可以避免在第一次完成之前手动进食，但玩家应该优先完成副本，尽快获得 *战斗被动槽* 。

对于副本的所有阶段，玩家可以通过手动吃食物生存，只要敌人的最大命中不超过玩家的最大**生命值**。

需要注意的是，这个副本只需要完成一次，所以策略根本不是死亡，而是快速完成。
对于玩家来说，确保他们有足够的**生命值**在攻击中生存比不通过手动进食重置攻击更重要。以下是四种不同的食物吃法：

1. *自动进食* - 让自动进食在不中断攻击的情况下治愈你。没有玩家输入！
2. *攻击后进食* - 等待攻击结束后再吃。通常在每次攻击后。
3. *连续进食* - 点击并按住食物按钮，连续吃食物。
4. *Spam Eat* _（仅限PC玩家）_ - 单击食物按钮一次，按Tab键一次，然后按Shift+Tab键一次以选择食物按钮。现在，按住空格键比简单地按住按钮吃得更快。单击其他位置将撤消此操作。

=== 奖励

完成**遁入迷雾**将永久将**幽暗水域**怪物添加到**屠杀者**任务的**大师级**。
这些怪物都有特定的弱点，并因玩家使用错误的战斗风格来对付他们而受到严厉惩罚，这使得使用**自动屠杀者**来满足解锁**屠杀者装备升级套件（大师）**的40任务要求变得更加困难。
如果需要，**险恶山脉**主任务可以在ITM完成之前完成，尽管这不是必需的。

完成**遁入迷雾**还允许玩家使用**被动装备插槽****巴勃罗**是通过完成副本5次单独获得的。

== 统计和缓冲

=== 最低要求

完成这个副本的唯一真正要求是**屠杀者90级**和足够的**生命值**和**伤害减免**不会被立即杀死。

完成这个副本的**推荐**等级大致为**攻击85级**，**力量85级**、**防御85级**和**950生命值**、**远程85级**以及**魔法85级**或**祝祭95级**，
玩家完成副本的每项技能都有可能降低10级，所以如果你的任何数据落后，那就不是世界末日。

=== 消耗品

* 食物：
** *鲸鱼* 或类似的东西。你需要一种食物，它可以一次治愈大量的生命值，这样无论发生什么，只要点击一下就能治愈你的绝大多数生命值。
* 药剂：
** *钻石运势药水* 适用于整个副本。
* 召唤石板：
** *龙* 和 *牛头人*、*半人马* 或 *女巫*。
* 祝祭：
** 以下将针对每个Boss阶段逐一概述这些内容。
** 不建议使用**防御相关祝祭**，以免发生故障。有很多方法可以确保你不会死，失去其中一个祝祭的效果实际上会增加你的死亡几率。
* 可消费插槽：
** *磨刀石*
** *巫师卷轴* - 可以跳过这些卷轴，因为它们不会给DPS带来提升
* *钻石运势药水* 和 *龙石板* *是这个副本最重要的增益*，药剂会大大增加你实际打击敌人的次数，石板会通过自己的攻击增加很多额外伤害，增加你的伤害和精度，龙的燃烧效果可以帮助你快速降低BOSS的生命值，这样你就可以减少在高强度痛苦中花费的时间。

=== 灵巧

虽然灵巧有助于提供有用的战斗奖励，但它主要有助于降低尝试遁入迷雾所需的生命值。通常，仅为遁入迷雾切换灵巧并不十分重要。

[%autowidth]
|===
|级别|障碍|理由
|1|任意 .2+|
|2|任意
|3|管道攀爬|唯一提供战斗加成的障碍物。
|4|煤炭阵|没有负奖金
|5|岩壁平衡|一定要记住你的生命值/伤害减免伤害计算中的生命值增加。
|6|崎岖水域|Lake Swim通常在你的等级更高的情况下更有用，因为你的生命值增加的效果会相应降低。
.2+.^|7|巨石陷阱 .2+.^|没有负面伤害修正。
|激流陷阱
|8|木筏建造|额外伤害和生命值。
.2+.^|9|冰川跳跃 .2+.^|冰霜跳跃通常是这一层上使用的唯一障碍，现在真的没有理由停止使用它。
|穿越冻湖
.2+.^|10|熔岩瀑布躲避 .2+.^|从熔岩瀑布躲避改变这个障碍物是昂贵的，通常并不值得。
|海洋漂流
|被动
|战斗灵巧柱
|战斗灵巧柱是唯一的DPS灵巧柱，但如果你已经有了不同的灵巧柱，就没有必要使用它，因为它的奖金对这个副本没有特别的帮助。
|===

== 战斗细节

=== 痛苦的怪物

一般来说，第1-20波最好使用您最好的**魔法装备**和**古代魔法**完成，或者主动切换以利用**战斗三角**奖金。
通常，这些怪物不是很危险，换成正确的战斗风格，怪物就会摔倒。

强烈建议您在到达最终BOSS后，花时间计算每个阶段的伤害减免值和每次攻击的最大命中率。

=== 所有Boss阶段的注意事项

建议在痛苦积累的各个阶段，通常每10堆左右，制作一张带有有效自动进食阈值的笔记卡。
这意味着在90%、80%、70%、60%、50%的最大生命值下，记下你40%的生命值，然后记下或注意每个boss攻击的最大伤害值，这样你就可以做出比下面给出的一般建议更明智的决定。

如果在任何时候有疑问，请尝试在一次攻击结束后立即进食，不要过于依赖这一点，因为重置攻击也会消除在下一次攻击中使用特殊攻击的机会。

== 神秘人物-第一阶段

[%autowidth]
|===
|插槽 3.+^.^|物品（最有效 → 最无效）
|头盔 |神盔 |古代头盔 |龙之盔
|护甲 |神之护甲 |古代护甲 |龙之护甲
|护腿 |神之护腿 |古代护腿(镀金) |龙之护腿(镀金)
|靴子 |拉格纳神靴子 |特兰神灵靴子 |龙之靴子(镀金)
|手套 |拉格纳神手套 |特兰神灵手套 |圣骑士手套
|斗篷 |炼狱斗篷 | 炼狱斗篷 |最大技能斗篷
|颈部 |元素圣斗士之怒 |精英防御护符 |精英荣耀护符
|戒指 |刀锋回响之戒 |战士之戒 |金蓝宝石戒指
|宝石 |敏捷宝石 |精准宝石 |回避宝石
|武器 |炼狱之爪 | 暗钢匕首 |落日刺剑
|盾牌 |龙焰盾牌 |地层盾牌 |龙盾(镀金)
|===

*Protect from Melee* 和 *Battleheart* 或你现有的最高等级近战祝祭。*Protect from Melee* 在这里很重要，因为它将BOSS的命中率设定为20%，显著降低了使用*Reap and Return* 时恢复生命的几率。
如果可能的话，当BOSS使用其他攻击时，将*Protect from Melee*替换为*Piety*可以帮助你额外挤出一些伤害。

在这里选择使用1小时武器是很重要的，因为它们的攻击间隔足够低，可以轻松地放下死亡标记。*特兰神剑* 和 *拉格纳神剑* (*特兰神剑 > 拉格纳神剑*) 都非常出色，可能能够更快地杀死BOSS，具体取决于你的特定属性，但它们的攻击间隔较慢，通常需要你更加注意吃饭的时间。

《Ultima Godsword》是一个出色的武器，通过造成可观的伤害量来规避2h武器的缺点。
如果拥有，这把武器应该被使用，然而，这不是必要或推荐的，因为这把武器可能很难获得。
不要使用任何其他提供特殊攻击的设备（*刀锋回响之环*），因为它们会降低使用Ultima特殊攻击的机会，从而破坏你的攻击潜力。

=== 第1阶段：能力和进食方法

* *死亡标记*：通常不危险，你希望在这次攻击击中你后尽快完成一次攻击。
未能在下一次攻击对你造成大量伤害之前移除那堆死亡标记会使事情变得异常复杂。
* *诅咒之刃*：中等堆叠的痛苦下危险，如果这次攻击造成的伤害超过你的自动进食阈值，则治疗到满血。
如果攻击造成至少60%的总生命值，则不危险，因为每次攻击都会使你的自动进食设定为至少80%的生命值。
*收获与回报*：在高堆的痛苦中很危险，如果有疑问，请暂停进食以避免死亡。
如果攻击造成的伤害至少达到你总生命值的60%，则不危险。

这个阶段是最困难的，如果你觉得有危险，谨慎行事可能是明智的。

=== 阶段 1: 挂机

WARNING: 在死亡标记的影响下手动进食仍然可能杀死你，如果试图挂机，请*不要*手动进食。

要完全挂机第1阶段，你需要一个间隔快于2.6秒的武器（所有高于这个标准的武器都符合条件）并且有足够的生命值和伤害减免来承受当你的生命值减少50%时的最大600点伤害，下表列出了一些常见的生命值检查点：

[%autowidth]
|===
|近战 |普通 |佩戴铺张之戒
|1000HP |67% |63%
|1040HP |66% |61%
|1070HP |65% |60%
|1100HP |64% |59%
|===

== 神秘人物 - 第二阶段

[%autowidth]
|===
|头盔 |阿里亚斯神头盔 |特兰神头盔 |屠杀者面罩（精英）
|护甲 |阿里亚斯神板护甲 |古代龙皮护甲(升级) |黑色龙皮护甲(升级)
|护腿 |阿里亚斯神板护腿 |古代龙皮护腿(升级) |黑色龙皮护腿(升级)
|靴子 |阿里亚斯神靴子 |特兰神靴子 |龙靴子(镀金)
|手套 |阿里亚斯神手套 |古代龙皮护腕(升级) |黑色龙皮护腕(升级)
|斗篷 |普拉特角 |炼狱斗篷 | 最大技能斗篷
|项链 |死眼护符 |元素圣斗士之怒 |精英远程护符
|戒指 |死眼戒指 |银绿戒指 |屏障之环
|宝石 |敏捷宝石 |精准宝石 |回避宝石
|武器 |古代的十字弓 |屠杀者的十字弓 |龙之十字弓
|盾牌 |鳞片盾牌 |古代龙皮盾牌(升级) |黑色龙皮盾牌(升级)
|弹药 |翡翠螺栓 |钻石螺栓 |绿宝石螺栓
|===

*Battleheart* 和 *Rigour* 或您可用的最高级别的远程祝祭。
像*Stormsnap*这样的2小时武器通常不错，但它们会要求你更加注意吃饭的时间，因为它们由于不能佩戴盾牌而具有较少的伤害减免，并且对于掉落成堆的死亡标记来说又慢又笨拙。

=== 第二阶段：能力和进食方法

* *死亡标记*：通常不危险，你希望在这次攻击击中你之后尽快完成一次攻击。
在下一次攻击对你造成大量伤害之前，未能移除那堆死亡标记会使事情变得异常复杂。
*隐藏危险*：通常没有危险，除非你没有移除死亡标记。
* *Shadowstep*：不会造成伤害，但是如果BOSS试图连续使用两次，她会使用普通攻击，她的普通攻击最大命中相当高，如果你未能移除死亡标记，她将变得更加危险。

这个阶段是迄今为止最简单的，因此完美优化它并不是至关重要的，几乎任何设置都应该没有真正的问题来清除这个阶段。
在这个阶段，进食应该几乎完全是不必要的。

警告：在*异常高的*痛苦堆叠下，并且在死亡标记的影响下，BOSS的普通攻击可能会造成超过你生命值的伤害。*只有在攻击连接之前，你手动食用并未能移除死亡标记，这才可能发生*。
如果发生这种情况，你必须跑来保证你的生存。

=== 第二阶段：挂机

警告：在死亡标记的影响下手动进食仍然可能杀死你，如果试图挂机，请*不要*手动进食。

要完全挂机第2阶段，你需要一个间隔快于3.9秒的武器（所有远程武器默认都满足这个条件）以及足够的生命值和伤害减免，以在生命值减少50%时承受最大772点伤害的攻击。下表列出了一些常见的生命值检查点：

[%autowidth]
|===
|远程 |普通 |带有铺张之戒
|1000HP |75% |71%
|1040HP |74% |70%
|1070HP |73% |69%
|1100HP |72% |68%
|===

== 阿雷尼亚 - 第3阶段

[%autowidth]
|===
|头盔 |格拉西娅神灵头盔 |古代巫师帽 |专家巫师帽
|护甲 |格拉西娅神灵护甲 |古代巫师长袍 |专家巫师长袍
|护腿 |格拉西娅神灵护腿 |古代巫师下装 |专家巫师下装
|靴子 |格拉西娅神灵靴子 |古代巫师靴子 |专家巫师靴子
|手套 |格拉西娅神灵手套 |特兰神灵手套 |古代龙皮护腕(升级)
|斗篷 |骷髅斗篷 |炼狱斗篷 |最大技能斗篷
|项链 |元素圣斗士之怒 |精英魔法护符 |精英防御护符
|名称 |巫师戒指 |银魔法带 |灵魂之力戒指
|宝石 |敏捷宝石 |规避宝石 |精准宝石
|武器 |元素充能魔杖 |魔法魔杖（强） |云爆法杖
|盾牌 |恶意防护盾 |魔法燃烧盾 |鳞盾
|===

使用灌注魔杖：

* *焚烧*、**狂风**或**风切**。
* *保护免受魔法* 和 *石肤*

使用**云爆法杖**：

* *水浪*和*狂怒II*。
* *Battleheart* 和 *Augury* 或你现有的最高等级魔法祝祭。

由于这个阶段相对较弱，在大多数情况下，云爆法杖应该能够造成足够的伤害，在Ahrenia成为一个真正的威胁之前杀死她。然而，由于这个阶段相对简单，建议使用古代魔法，因为这将允许你使用伤害减免药剂而不是钻石幸运，因为你的命中已经保证在20k+的准确率评级。

=== 第三阶段：能力和进食方法

* *暗影爆发*：在低层痛苦状态下可能很危险。
命中时，给予玩家-1%的准确率，最高可达50%。
为了在这种效果的最大堆栈中保证20k+的准确度，玩家必须拥有33,333的准确度评级。
遁入迷雾：不造成伤害。
每次敌人被击中时，给予他们+10%的伤害减免，因此，如果使用的是古代魔法，为了在持续时间内获得更有效的伤害，可能明智的做法是切换到*点燃*或*地震*。
* *坠落之光*: 并不危险。

=== 第三阶段：挂机

要完全挂机第3阶段，你只需要有足够的生命值和伤害减免来承受一次最大伤害为800的攻击，当你的生命值减少50%时，下表列出了一些常见的生命值检查点：

[%autowidth]
|===
|魔法 |正常 |佩戴铺张之戒
|1000HP |75% |72%
|1040HP |74% |71%
|1070HP |74% |70%
|1100HP |73% |70%
|===


